<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Domain\ModulosComunes\Productos\Models\CategoriaProducto;
use App\Domain\ModulosComunes\Productos\Models\SubcategoriaProducto;
use App\Domain\ModulosComunes\Productos\Models\Linea;
use App\Domain\ModulosComunes\Productos\Models\Destino;
use App\Domain\ModulosComunes\Productos\Models\ProductoTerminado;
use Illuminate\Support\Facades\DB;

class DispositivosSeeder extends Seeder
{
    public function run(): void



    {
    DB::table('PLL_dispositivos_mediciones')->insert([
            ['codigo' => 'PLL-BAL-001', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'V11P6', 'capacidadMedicion' => '1-6.000 g','rangoUso' => '100 - 1.500 g', 'areaUso' => '-' ,'responsable' => 'Jefe de Planta', 'baja' => '2018', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now(),],
            ['codigo' => 'PLL-BAL-002', 'dispositivo' => 'Balanza', 'marca' => 'Kretz', 'modelo' => '3200 C', 'capacidadMedicion' => '0.001-6 kg','rangoUso' => '0.075 - 1.8 kg', 'areaUso' => 'Envasado HTST' ,'responsable' => 'Jefe de Planta', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now(),],
            ['codigo' => 'PLL-BAL-003', 'dispositivo' => 'Balanza', 'marca' => 'Hi Weigh', 'modelo' => 'X1PE', 'capacidadMedicion' => '0.05-300 kg','rangoUso' => '1-200 kg', 'areaUso' => 'Almacen de Materia Prima' ,'responsable' => 'Encargado de Almacen', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now(),],
            ['codigo' => 'PLL-BAL-004', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'V11P15', 'capacidadMedicion' => '2-15.000 g','rangoUso' => '5-14.000 g', 'areaUso' => 'Fraccionado' ,'responsable' => 'Jefe de Planta', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now(),],
            ['codigo' => 'PLL-BAL-005', 'dispositivo' => 'Balanza', 'marca' => 'Kretz', 'modelo' => '3200 C', 'capacidadMedicion' => '0.001-6 kg','rangoUso' => '0.001- 5 kg', 'areaUso' => 'Almacen de Materia Prima' ,'responsable' => 'Encargado de Almacen', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now(),],
            ['codigo' => 'PLL-BAL-006', 'dispositivo' => 'Balanza', 'marca' => 'Clever', 'modelo' => 'TCS -A2', 'capacidadMedicion' => '0.1-300 kg','rangoUso' => '1-200 kg', 'areaUso' => 'Almacen de Materia Prima' ,'responsable' => 'Encargado de Almacen', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-007', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'V11P6', 'capacidadMedicion' => '1-6.000 g','rangoUso' => '1-5.000 g', 'areaUso' => 'Sala de envasado UHT' ,'responsable' => 'Jefe de Planta', 'baja' => '2024', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-008', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'SP 202', 'capacidadMedicion' => '0.01-200 g','rangoUso' => '0.01-150 g', 'areaUso' => 'Diseño y Desarrollo' ,'responsable' => 'Enc. Dis. y Desarrollo', 'baja' => '2024', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-009', 'dispositivo' => 'Balanza', 'marca' => 'Clever', 'modelo' => 'TCS -A2', 'capacidadMedicion' => '0.01-300 kg','rangoUso' => '5-200 kg', 'areaUso' => 'Almacen de Materia Prima' ,'responsable' => 'Encargado de Almacen', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-010', 'dispositivo' => 'Balanza', 'marca' => 'China', 'modelo' => '--', 'capacidadMedicion' => '0,1-300 kg','rangoUso' => '10-50 kg', 'areaUso' => 'Sala de Ultra Pasteurizado' ,'responsable' => 'Jefe de Planta', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-011', 'dispositivo' => 'Balanza', 'marca' => 'Adam', 'modelo' => 'HCB 302', 'capacidadMedicion' => '0.01-300 g','rangoUso' => '0,01-50 g', 'areaUso' => 'Diseño y Desarrollo' ,'responsable' => 'Enc. Dis. y Desarrollo', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-012', 'dispositivo' => 'Balanza', 'marca' => 'Clever', 'modelo' => '--', 'capacidadMedicion' => '1-30.000 g','rangoUso' => '1-30.000 g', 'areaUso' => 'Almacen de Materia Prima' ,'responsable' => 'Encargado de Almacen', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-013', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'TRAVELER TA302', 'capacidadMedicion' => '0,01-300 g','rangoUso' => '1-100 g', 'areaUso' => 'Laboratorio - Materia Prima' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-014', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'TRAVELER TA302', 'capacidadMedicion' => '0,01-300 g','rangoUso' => '30-300 g', 'areaUso' => 'Laboratorio - Microbiología' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '2025', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-015', 'dispositivo' => 'Balanza', 'marca' => 'Clever', 'modelo' => '--', 'capacidadMedicion' => '5-40000 g','rangoUso' => '70-3000 g', 'areaUso' => 'Laboratorio C. de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '2025', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-016', 'dispositivo' => 'Balanza', 'marca' => 'Clever', 'modelo' => '--', 'capacidadMedicion' => '5-40000 g','rangoUso' => '5-1000 g', 'areaUso' => 'Envasado de quesos' ,'responsable' => 'Encargado de Quesos', 'baja' => '2025', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-017', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'V12PG', 'capacidadMedicion' => '0,001-6 kg','rangoUso' => '0,001-6 kg', 'areaUso' => 'Laboratorio de Microbiologia' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-018', 'dispositivo' => 'Balanza', 'marca' => 'AND', 'modelo' => 'EJ-610', 'capacidadMedicion' => '0,1-610 g','rangoUso' => '30-300 g', 'areaUso' => 'Laboratorio de Microbiologia' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-019', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'V12PG', 'capacidadMedicion' => '0,001-6 kg','rangoUso' => '0,001-6 kg', 'areaUso' => 'Envasado de Vasos' ,'responsable' => 'Jefe de Planta', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-020', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'V22XWE15T', 'capacidadMedicion' => '0,002-15 kg','rangoUso' => '0,002-15 kg', 'areaUso' => 'Fracionado' ,'responsable' => 'Jefe de Planta', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-021', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'V22XWE15T', 'capacidadMedicion' => '0,002-15 kg','rangoUso' => '--', 'areaUso' => 'Diseño y Desarrollo' ,'responsable' => 'Enc. Dis. y Desarrollo', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-022', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'NV621', 'capacidadMedicion' => '0,1-620 g','rangoUso' => '0,1-620 g', 'areaUso' => 'Fracionado' ,'responsable' => 'Jefe de Planta', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-023', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'V12PG', 'capacidadMedicion' => '0,001-6 kg','rangoUso' => '0,001-6 kg', 'areaUso' => 'Laboratorio - Microbiología' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '2024', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-024', 'dispositivo' => 'Balanza', 'marca' => 'Metler Toledo', 'modelo' => 'BPA 121', 'capacidadMedicion' => '0,1-6000 g','rangoUso' => '0,1-1000 g', 'areaUso' => 'Laboratorio C. de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-025', 'dispositivo' => 'Balanza', 'marca' => 'Metler Toledo', 'modelo' => 'BPA 121', 'capacidadMedicion' => '0,1-6000 g','rangoUso' => '0,1-1000 g', 'areaUso' => 'Envasado UHT' ,'responsable' => 'Jefe de Planta', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-BAL-026', 'dispositivo' => 'Balanza', 'marca' => 'Ohaus', 'modelo' => 'SP 202', 'capacidadMedicion' => '0.01-200 g','rangoUso' => '0.01-150 g', 'areaUso' => 'Diseño y Desarrollo' ,'responsable' => 'Enc. Dis. y Desarrollo', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TER-001', 'dispositivo' => 'Termómetro', 'marca' => 'Testo', 'modelo' => '925', 'capacidadMedicion' => '-50-1000°c','rangoUso' => '0 - 50 °c', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de Planta', 'baja' => '2024', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TER-002', 'dispositivo' => 'Termómetro', 'marca' => 'Testo', 'modelo' => '925', 'capacidadMedicion' => '-50-1000°c','rangoUso' => '0 - 50 °c', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TER-003', 'dispositivo' => 'Termómetro', 'marca' => 'Testo', 'modelo' => '174T', 'capacidadMedicion' => '-30-70 °C','rangoUso' => '-30-0 °C', 'areaUso' => 'Almacen de Materia Prima' ,'responsable' => 'Encargado de Almacen', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TER-004', 'dispositivo' => 'Termómetro', 'marca' => 'Testo', 'modelo' => '925', 'capacidadMedicion' => '-50-1000 °C','rangoUso' => '--', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '2024', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TER-005', 'dispositivo' => 'Termómetro', 'marca' => 'Testo', 'modelo' => '925', 'capacidadMedicion' => '-50-1000 °C','rangoUso' => '0-50 °C', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '2024', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TER-006', 'dispositivo' => 'Termómetro', 'marca' => 'Testo', 'modelo' => '925', 'capacidadMedicion' => '-50-1000 °C','rangoUso' => '0-50 °C', 'areaUso' => 'Producción' ,'responsable' => 'Produccion', 'baja' => '2024', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TER-007', 'dispositivo' => 'Termómetro', 'marca' => 'HANNA', 'modelo' => 'Checktemp1', 'capacidadMedicion' => '-50-150 °C','rangoUso' => '0-50 °C', 'areaUso' => 'Producción' ,'responsable' => 'Supervisor de Produccion', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TER-008', 'dispositivo' => 'Termómetro', 'marca' => 'HANNA', 'modelo' => 'Checktemp1', 'capacidadMedicion' => '-50-150 °C','rangoUso' => '0-50 °C', 'areaUso' => 'Producción' ,'responsable' => 'Supervisor de Produccion', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TER-009', 'dispositivo' => 'Termómetro', 'marca' => 'HANNA', 'modelo' => 'Checktemp1', 'capacidadMedicion' => '-50-150 °C','rangoUso' => '0-50 °C', 'areaUso' => 'Producción' ,'responsable' => 'Supervisor de Produccion', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TER-010', 'dispositivo' => 'Termómetro', 'marca' => 'HANNA', 'modelo' => 'Checktemp1', 'capacidadMedicion' => '-50-150 °C','rangoUso' => '0-50 °C', 'areaUso' => 'Producción' ,'responsable' => 'Supervisor de Produccion', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TER-011', 'dispositivo' => 'Termómetro', 'marca' => 'HANNA', 'modelo' => 'Checktemp1', 'capacidadMedicion' => '-50-150 °C','rangoUso' => '0-50 °C', 'areaUso' => 'Laboratorio - Materia Prima' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-TERH-001', 'dispositivo' => 'Termohigrometro', 'marca' => 'Testo', 'modelo' => '174H', 'capacidadMedicion' => '-20 -70 °C / 0 - 100 %HR','rangoUso' => '-10 - 45 °C / 0 - 100 %HR', 'areaUso' => 'Almacen de Materia Prima' ,'responsable' => 'Encargado de Almacen', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-REF-001', 'dispositivo' => 'Refractometro', 'marca' => 'Atago', 'modelo' => 'Pocket', 'capacidadMedicion' => '0-53 brix','rangoUso' => '0-20 brix', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '--', 'observaciones' => 'EN DESHUSO', 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-REF-002', 'dispositivo' => 'Refractometro', 'marca' => 'Atago', 'modelo' => 'Pocket', 'capacidadMedicion' => '0-53 brix','rangoUso' => '0-20 brix', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '--', 'observaciones' => 'EN DESHUSO', 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-REF-003', 'dispositivo' => 'Refractometro', 'marca' => 'Atago', 'modelo' => 'Pocket', 'capacidadMedicion' => '0-53 brix','rangoUso' => '0-20 brix', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => 'EN DESHUSO', 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-REF-004', 'dispositivo' => 'Refractometro', 'marca' => 'Atago', 'modelo' => 'Pocket', 'capacidadMedicion' => '0-53 brix','rangoUso' => '0-20 brix', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '--', 'observaciones' => 'EN DESHUSO', 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-REFM-001', 'dispositivo' => 'Refractometro', 'marca' => 'Hanna Ins.', 'modelo' => 'HI 96801', 'capacidadMedicion' => '0-85 brix','rangoUso' => 'N/A', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '--', 'observaciones' => 'EN DESHUSO', 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-REFM-002', 'dispositivo' => 'Refractometro', 'marca' => 'Hanna Ins.', 'modelo' => 'HI 96801', 'capacidadMedicion' => '0-85 brix','rangoUso' => 'N/A', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '2024', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-REFM-003', 'dispositivo' => 'Refractometro', 'marca' => 'Hanna Ins.', 'modelo' => 'HI 96801', 'capacidadMedicion' => '0-85 brix','rangoUso' => 'N/A', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '2024', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-REFM-004', 'dispositivo' => 'Refractometro', 'marca' => 'Hanna Ins.', 'modelo' => 'HI 96811', 'capacidadMedicion' => '0-50 brix','rangoUso' => 'N/A', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '--', 'observaciones' => 'EN DESHUSO', 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-REFM-005', 'dispositivo' => 'Refractometro', 'marca' => 'Hanna Ins.', 'modelo' => 'HI 96812', 'capacidadMedicion' => '0-50 brix','rangoUso' => 'N/A', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-REFM-006', 'dispositivo' => 'Refractometro', 'marca' => 'Hanna Ins.', 'modelo' => 'HI 96813', 'capacidadMedicion' => '0-50 brix','rangoUso' => 'N/A', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-REFM-007', 'dispositivo' => 'Refractometro', 'marca' => 'Hanna Ins.', 'modelo' => 'HI 96814', 'capacidadMedicion' => '0-50 brix','rangoUso' => 'N/A', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-PHM-001', 'dispositivo' => 'pH metro', 'marca' => 'Metler Toledo', 'modelo' => 'Seven Easy', 'capacidadMedicion' => '0 - 14','rangoUso' => '3-7.4', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-PHM-002', 'dispositivo' => 'pH metro', 'marca' => 'Hanna Ins.', 'modelo' => 'Edge ST 0,3716', 'capacidadMedicion' => '0 - 14','rangoUso' => '3-7.4', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-PHM-003', 'dispositivo' => 'pH metro', 'marca' => 'Metler Toledo', 'modelo' => 'Seven Compact', 'capacidadMedicion' => '0 - 14','rangoUso' => '3-7.4', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-MIC-001', 'dispositivo' => 'Micrometro', 'marca' => 'Mitutoyo', 'modelo' => '7327A', 'capacidadMedicion' => '0-1 mm','rangoUso' => '0,05 - 0,1 mm', 'areaUso' => 'Laboratorio - Materia Prima' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['codigo' => 'PLL-CRI-001', 'dispositivo' => 'Crióscopo', 'marca' => 'Funke Gerber', 'modelo' => 'CryoStar I', 'capacidadMedicion' => '0,00 °C hasta -1,50 °C','rangoUso' => '0,00 - (-0,75) °C', 'areaUso' => 'Laboratorio de C.de Calidad' ,'responsable' => 'Jefe de C. de Calidad', 'baja' => '-', 'observaciones' => NULL, 'created_at' => now(), 'updated_at' => now()]
        ]);


    

    }



}
