<?php

namespace Database\Seeders;

use App\Domain\PlantaLacteos\Models\ItemMateriaPrima;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

class LacteosSeeder4 extends Seeder
{


    private $categorias = [
        'ADITIVOS' => 1,
        'CEREALES' => 2,
        'COLORANTES' => 3,
        'CONSERVANTES' => 4,
        'CULTIVOS' => 5,
        'EDULCORANTES' => 6,
        'ENTURBIANTES' => 7,
        'ENVASES' => 8,
        'ESENCIAS' => 9,
        'ESTABILIZANTES' => 10,
        'FORTIFICANTES' => 11,
        'HARINAS' => 12,
        'PULPAS' => 13,
        'REGULADORES DE ACIDEZ' => 14,
        'SUSTITUTO LACTEO' => 15,
        'DETERGENTES' => 16,
        'SUSTANCIAS QUÍMICAS' => 17,
    ];

    private $unidades = [
        'Mililitros' => 4,
        'Gramos' => 2,
        'Litro' => 3,
        'Kilogramo' => 1,
        'Unidad' => 5,
    ];

    public function run()
    {
        $materiasPrimas = [
            ['codigo' => 'MP00001', 'nombre' => 'HARINA DE TRIGO TIPO 1', 'descripcion' => 'HARINA TIPO A', 'categoria' => 'HARINAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00004', 'nombre' => 'HARINA DE LINAZA', 'descripcion' => 'HARINA DE LINAZA', 'categoria' => 'HARINAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00005', 'nombre' => 'HARINA DE ARROZ', 'descripcion' => 'HARINA DE ARROZ', 'categoria' => 'HARINAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00010', 'nombre' => 'HARINA DE AMARANTO', 'descripcion' => 'HARINA DE AMARANTO', 'categoria' => 'HARINAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00012', 'nombre' => 'HARINA DE AVENA', 'descripcion' => 'HARINA DE AVENA', 'categoria' => 'HARINAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00020', 'nombre' => 'PITO DE CAÑAHUA', 'descripcion' => 'PITO DE CAÑAHUA', 'categoria' => 'HARINAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00038', 'nombre' => 'AZUCAR', 'descripcion' => 'AZUCAR', 'categoria' => 'EDULCORANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00040', 'nombre' => 'EDULCORANTE TIPO 1', 'descripcion' => 'EDULDIET', 'categoria' => 'EDULCORANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00041', 'nombre' => 'EDULCORANTE TIPO 2', 'descripcion' => 'EMULSWEET 3609', 'categoria' => 'EDULCORANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00042', 'nombre' => 'GLUCOSA LIQUIDA', 'descripcion' => 'GLUCOSA LIQUIDA', 'categoria' => 'EDULCORANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00045', 'nombre' => 'MANTECA TIPO 1', 'descripcion' => 'MANTECA KARINA', 'categoria' => 'ADITIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00056', 'nombre' => 'BICARBONATO DE SODIO', 'descripcion' => 'BICARBONATO DE SODIO', 'categoria' => 'REGULADORES DE ACIDEZ', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00066', 'nombre' => 'ESENCIA VAINILLA TIPO 1', 'descripcion' => 'ESENCIA DE VAINILLA', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00070', 'nombre' => 'ESENCIA CARAMELO TIPO 1', 'descripcion' => 'ESENCIA CARAMELO LECHE SOYA', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00071', 'nombre' => 'ESENCIA CHOCOLATE TIPO 1', 'descripcion' => 'ESENCIA CHOCOLATE DEGUSA SOYA 20860', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00072', 'nombre' => 'ESENCIA COOKIE CHOCOLATE TIPO 1', 'descripcion' => 'ESENCIA COOKIE CHOCOLATE', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00073', 'nombre' => 'ESENCIA FRUTILLA TIPO 2', 'descripcion' => 'ESENCIA FRUTILLA NATURAL 6876B SOYA', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00079', 'nombre' => 'ESENCIA CHOCOLATE TIPO 3', 'descripcion' => 'ESENCIA CHOCOLATE 9121', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00082', 'nombre' => 'ESENCIA CLAVO CANELA TIPO 1', 'descripcion' => 'ESENCIA CLAVO CANELA', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00083', 'nombre' => 'ESENCIA DE AVENA TIPO 1', 'descripcion' => 'ESENCIA DE AVENA 504734 MYLNER', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00084', 'nombre' => 'ESENCIA CHIRIMOYA TIPO 1', 'descripcion' => 'ESENCIA DE CHIRIMOYA FC636200', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00085', 'nombre' => 'ESENCIA CHIRIMOYA TIPO 2', 'descripcion' => 'ESENCIA CHIRIMOYA FC52900', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00086', 'nombre' => 'ESENCIA MANZANA TIPO 2', 'descripcion' => 'ESENCIA MANZANA VERDE', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00095', 'nombre' => 'ESENCIA COCO TIPO 2', 'descripcion' => 'ESENCIA COCO (11AC4275)', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00096', 'nombre' => 'ESENCIA LIMON TIPO 3', 'descripcion' => 'ESENCIA LIMON 8456', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00101', 'nombre' => 'ESENCIA PIÑA TIPO 2', 'descripcion' => 'ESENCIA PIÑA 21916077', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00102', 'nombre' => 'ESENCIA MORA TIPO 1', 'descripcion' => 'ESENCIA MORA 92455277', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00103', 'nombre' => 'ESENCIA UVA TIPO 1', 'descripcion' => 'ESENCIA UVA 92562677', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00104', 'nombre' => 'ESENCIA NARANJA TIPO 3', 'descripcion' => 'ESENCIA NARANJA 13469277', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00109', 'nombre' => 'ESENCIA NARANJA TIPO 4', 'descripcion' => 'ESENCIA NARANJA A', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00110', 'nombre' => 'ESENCIA MANDARINA TIPO 1', 'descripcion' => 'ESENCIA MANDARINA 80014777', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00111', 'nombre' => 'ESENCIA CITRUS PUNCH TIPO 1', 'descripcion' => 'ESENCIA CITRUS PUNCH TURBIA', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00113', 'nombre' => 'ESENCIA CANELA EN POLVO TIPO 1', 'descripcion' => 'ESENCIA DE CANELA EN POLVO', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00118', 'nombre' => 'ESENCIA DURAZNO TIPO 2', 'descripcion' => 'ESENCIA DURAZNO 11AC4308 LTS', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00120', 'nombre' => 'ESENCIA LIMON TIPO 1', 'descripcion' => 'ESENCIA DE LIMON (SAPORITI)', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00121', 'nombre' => 'SABORIZANTE MIX DE FRUTOS ROJOS TIPO 1', 'descripcion' => 'SAB.MIX DE FRUTOS ROJOS 11AC4348', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00123', 'nombre' => 'ESENCIA MANZANA TIPO 1', 'descripcion' => 'ESENCIA MANZANA GOLDEN 71789', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00124', 'nombre' => 'ESENCIA MANGO TIPO 1', 'descripcion' => 'ESENCIA MANGO 80205177', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00128', 'nombre' => 'ESENCIA DURAZNO TIPO 3', 'descripcion' => 'ESENC.DURAZNO ZY1372379', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00129', 'nombre' => 'COLORANTE AMARILLO TIPO 1', 'descripcion' => 'COLORANTE AMARILLO HUEVO', 'categoria' => 'COLORANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00131', 'nombre' => 'COLORANTE CHOCOLATE TIPO 1', 'descripcion' => 'COLORANTE CHOCOLATE', 'categoria' => 'COLORANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00132', 'nombre' => 'COLORANTE ROJO TIPO 1', 'descripcion' => 'COLORANTE ROJO FRESA', 'categoria' => 'COLORANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00133', 'nombre' => 'COLORANTE AMARILLO TIPO 2', 'descripcion' => 'TARTRAZINA', 'categoria' => 'COLORANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00134', 'nombre' => 'COLORANTE UVA TIPO 1', 'descripcion' => 'COLORANTE UVA', 'categoria' => 'COLORANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00135', 'nombre' => 'COLORANTE VERDE TIPO 1', 'descripcion' => 'COLORANTE VERDE MANZANA', 'categoria' => 'COLORANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00137', 'nombre' => 'COLORANTE CARMIN TIPO 1', 'descripcion' => 'COLORANTE MONTECARMIN 11325', 'categoria' => 'COLORANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00138', 'nombre' => 'COLORANTE BIXIN TIPO 1', 'descripcion' => 'COLORANTE MONTEBIXIN 5562', 'categoria' => 'COLORANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00139', 'nombre' => 'COLORANTE AZUL TIPO 1', 'descripcion' => 'COLORANTE AZUL BRILLANTE', 'categoria' => 'COLORANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00140', 'nombre' => 'COLORANTE NARANJA SUNSET TIPO 1', 'descripcion' => 'COLORANTE NARANJA SUNSET', 'categoria' => 'COLORANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00144', 'nombre' => 'CARBOXI METIL CELULOSA CMC', 'descripcion' => 'C.M.C. CARBOXI METIL CELULOSA', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00145', 'nombre' => 'ESTABILIZANTE TIPO 4', 'descripcion' => 'GRINDSTED ESTABILIZANTE YOGUR', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00146', 'nombre' => 'ESTABILIZANTE TIPO 2', 'descripcion' => 'PALSGAARD 5820 EMULSIONANTE', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00147', 'nombre' => 'ESTABILIZANTE TIPO 3', 'descripcion' => 'PALSGAARD P5834', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00148', 'nombre' => 'EMULSIFICANTE TIPO 1', 'descripcion' => 'EMULGEL', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00150', 'nombre' => 'GOMA XANTHAN', 'descripcion' => 'GOMA XANTHAN', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00151', 'nombre' => 'COLAGENO HIDROLIZADO', 'descripcion' => 'COLAGENO HIDROLIZADO', 'categoria' => 'ADITIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00152', 'nombre' => 'GELATINA NEUTRA', 'descripcion' => 'GELATINA SIN SABOR', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00153', 'nombre' => 'MAICENA', 'descripcion' => 'MAICENA', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00155', 'nombre' => 'MALTODEXTRINA', 'descripcion' => 'MALTODEXTRINA', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00156', 'nombre' => 'CARRAGENINA', 'descripcion' => 'CARRAGENINA', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00157', 'nombre' => 'PECTINA CITRICA', 'descripcion' => 'PECTINA CITRICA', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00158', 'nombre' => 'ETENIA', 'descripcion' => 'ETENIA 457', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00160', 'nombre' => 'ESTABILIZANTE TIPO 1', 'descripcion' => 'SHEREXYO 2530B (ESTABILIZANTE)', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00171', 'nombre' => 'CULTIVO LACTEO TIPO 1', 'descripcion' => 'CULTIVO LYOFAST Y 4.36 A 10UC', 'categoria' => 'CULTIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00172', 'nombre' => 'CULTIVO LACTEO TIPO 2', 'descripcion' => 'CULTIVO LYOFAST Y 4.56 B 10UC', 'categoria' => 'CULTIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00173', 'nombre' => 'CULTIVO LACTEO TIPO 3', 'descripcion' => 'CULTIVO LYOFAST Y 4.56 B 5UC', 'categoria' => 'CULTIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00191', 'nombre' => 'FOSFATO TRICALCICO', 'descripcion' => 'FOSFATO TRICALCICO', 'categoria' => 'FORTIFICANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00192', 'nombre' => 'SULFATO FERROSO', 'descripcion' => 'SULFATO FERROSO', 'categoria' => 'FORTIFICANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00194', 'nombre' => 'FUMARATO FERROSO', 'descripcion' => 'FUMARATO FERROSO', 'categoria' => 'FORTIFICANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00195', 'nombre' => 'VITAMINA A TIPO 1', 'descripcion' => 'VITAMINA A POLVO SOLUBLE', 'categoria' => 'FORTIFICANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00196', 'nombre' => 'ACIDO FOLICO', 'descripcion' => 'ACIDO FOLICO', 'categoria' => 'FORTIFICANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00197', 'nombre' => 'ACIDO FUMARICO', 'descripcion' => 'ACIDO FUMARICO', 'categoria' => 'REGULADORES DE ACIDEZ', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00198', 'nombre' => 'SULFATO DE ZING', 'descripcion' => 'SULFATO DE ZINC', 'categoria' => 'FORTIFICANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00201', 'nombre' => 'ACIDO MALICO', 'descripcion' => 'ACIDO MALICO', 'categoria' => 'REGULADORES DE ACIDEZ', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00202', 'nombre' => 'ACIDO ASCORBICO', 'descripcion' => 'ACIDO ASCORBICO', 'categoria' => 'FORTIFICANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00203', 'nombre' => 'ACIDO CITRICO', 'descripcion' => 'ACIDO CITRICO', 'categoria' => 'REGULADORES DE ACIDEZ', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00204', 'nombre' => 'ACIDO LACTICO', 'descripcion' => 'ACIDO LACTICO', 'categoria' => 'REGULADORES DE ACIDEZ', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00205', 'nombre' => 'CITRATO DE SODIO', 'descripcion' => 'CITRATO DE SODIO', 'categoria' => 'REGULADORES DE ACIDEZ', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00207', 'nombre' => 'POLIFOSFATO DE SODIO', 'descripcion' => 'POLIFOSFATO DE SODIO', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00213', 'nombre' => 'SAL YODADA', 'descripcion' => 'SAL YODADA', 'categoria' => 'ADITIVOS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00216', 'nombre' => 'COCOA ALCALINA TIPO 1', 'descripcion' => 'COCOA ALCALINA', 'categoria' => 'ADITIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00219', 'nombre' => 'LECHE EN POLVO TIPO 1', 'descripcion' => 'LECHE EN POLVO DESCREMADA', 'categoria' => 'SUSTITUTO LACTEO', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00221', 'nombre' => 'LECHE EN POLVO TIPO 2', 'descripcion' => 'KERRY 250', 'categoria' => 'SUSTITUTO LACTEO', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00225', 'nombre' => 'SORBATO DE POTASIO', 'descripcion' => 'SORBATO DE POTASIO', 'categoria' => 'CONSERVANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00226', 'nombre' => 'CONSERVANTE LIQUIDO', 'descripcion' => 'BACOXIN BACTERICIDA', 'categoria' => 'CONSERVANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00227', 'nombre' => 'BENZOATO DE SODIO', 'descripcion' => 'BENZOATO DE SODIO', 'categoria' => 'CONSERVANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00228', 'nombre' => 'NATAMICINA', 'descripcion' => 'NATAMICINA', 'categoria' => 'CONSERVANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00241', 'nombre' => 'CEREAL EN POLVO (CERELAC)', 'descripcion' => 'CERELAC', 'categoria' => 'CEREALES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00242', 'nombre' => 'CEREAL COPOS DE MAIZ', 'descripcion' => 'COPOS DE MAIZ (CEREAL)', 'categoria' => 'CEREALES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00249', 'nombre' => 'ANTIESPUMANTE', 'descripcion' => 'ANTIESPUMANTE', 'categoria' => 'ADITIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00250', 'nombre' => 'EDTA DISODICO', 'descripcion' => 'EDTA DISODICO', 'categoria' => 'REGULADORES DE ACIDEZ', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00251', 'nombre' => 'ENTURBIANTE EN POLVO', 'descripcion' => 'ENTURBIANTE EN POLVO', 'categoria' => 'ENTURBIANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00252', 'nombre' => 'ENTURBIANTE LIQUIDO', 'descripcion' => 'ENTURBIANTE NEUTRO 2E017500', 'categoria' => 'ENTURBIANTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00257', 'nombre' => 'CANELA MOLIDA', 'descripcion' => 'CANELA MOLIDA', 'categoria' => 'ADITIVOS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00261', 'nombre' => 'CUCHARITA PLASTICA 9CM', 'descripcion' => 'CUCHARITA PLASTICA 9CM', 'categoria' => 'ENVASES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00282', 'nombre' => 'CULTIVO LACTEO TIPO 5', 'descripcion' => 'CULTIVO LYOFAST Y430A', 'categoria' => 'CULTIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00284', 'nombre' => 'ESENCIA DURAZNO TIPO 4', 'descripcion' => 'ESENCIA DURAZNO DZ-922', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00285', 'nombre' => 'SABOR DULCE MELAZA', 'descripcion' => 'SABOR DULCE MELAZA', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00286', 'nombre' => 'SABORIZANTE MANZANA TIPO 1', 'descripcion' => 'SABORIZANTE MANZANA ROJA', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00287', 'nombre' => 'SABORIZANTE MANZANA TIPO 2', 'descripcion' => 'SABORIZANTE MANZANA', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00288', 'nombre' => 'ESENCIA DURAZNO TIPO 5', 'descripcion' => 'ESENCIA DURAZNO 2D1912-00', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00289', 'nombre' => 'SABORIZANTE MARACUYA TIPO 1', 'descripcion' => 'SABORIZANTE MARACUYA M76986', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00290', 'nombre' => 'AROMA MARACUYA TIPO 1', 'descripcion' => 'AROMA DE MARACUYA FC982873', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00295', 'nombre' => 'PULPA DE DURAZNO', 'descripcion' => 'PULPA DE DURAZNO', 'categoria' => 'PULPAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00296', 'nombre' => 'ESTABILIZANTE TIPO 5', 'descripcion' => 'DOREMIX FHA', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00297', 'nombre' => 'CULTIVO LACTEO TIPO 7', 'descripcion' => 'CULTIVO LYOFAST Y 480F 5UC', 'categoria' => 'CULTIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00298', 'nombre' => 'ESENCIA FRESA TIPO 2', 'descripcion' => 'ESENCIA FRESA 86753A', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00301', 'nombre' => 'STEVIA EN POLVO', 'descripcion' => 'STEVIA EN POLVO', 'categoria' => 'EDULCORANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00303', 'nombre' => 'CULTIVO LACTEO TIPO 8', 'descripcion' => 'CULTIVO LYOFAST Y4.50B 10UC', 'categoria' => 'CULTIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00305', 'nombre' => 'ESENCIA DAMASCO TIPO 1', 'descripcion' => 'ESENCIA DAMASCO TIPO 1', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00306', 'nombre' => 'CHIA TOSTADA', 'descripcion' => 'CHIA TOSTADA', 'categoria' => 'HARINAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00308', 'nombre' => 'CUAJO ALBAMAX', 'descripcion' => 'CUAJO ALBAMAX', 'categoria' => 'ADITIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00310', 'nombre' => 'CULTIVO LRB', 'descripcion' => 'CULTIVO LRB', 'categoria' => 'CULTIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00311', 'nombre' => 'ESTABILIZANTE TIPO 6 SHEREX 21', 'descripcion' => 'ESTABILIZANTE TIPO 6 SHEREX 21', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00312', 'nombre' => 'ESENCIA PLATANO', 'descripcion' => 'ESENCIA PLATANO', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00313', 'nombre' => 'ESENCIA FRAMBRUESA', 'descripcion' => 'ESENCIA FRAMBRUESA', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00321', 'nombre' => 'LACTASA', 'descripcion' => 'LACTASA', 'categoria' => 'ADITIVOS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00323', 'nombre' => 'ESENCIA MORA 3870-01 TIPO2', 'descripcion' => 'ESENCIA MORA 3870-01 TIPO2', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00325', 'nombre' => 'ESTABILIZANTE TIPO 7 RECODAM CN2', 'descripcion' => 'ESTABILIZANTE TIPO 7 RECODAM CN2', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00329', 'nombre' => 'ACIDO FOSFORICO', 'descripcion' => 'ACIDO FOSFORICO', 'categoria' => 'REGULADORES DE ACIDEZ', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00330', 'nombre' => 'CULTIVO LACTEO TIPO 9', 'descripcion' => 'CULTIVO LACTOFERM YO-441', 'categoria' => 'CULTIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00331', 'nombre' => 'CULTIVO LACTEO TIPO 10', 'descripcion' => 'CULTIVO LYOFAST YAB 450BB 5UC', 'categoria' => 'CULTIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00335', 'nombre' => 'CEREAL HOJUELAS DE CHOCOLATE', 'descripcion' => 'CEREAL HOJUELAS DE CHOCOLATE', 'categoria' => 'CEREALES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00336', 'nombre' => 'FUMARATO DE CALCIO', 'descripcion' => 'FUMARATO DE CALCIO', 'categoria' => 'FORTIFICANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00337', 'nombre' => 'ESENCIA NARANJA TIPO 5', 'descripcion' => 'ESENCIA NARANJA 1208', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00341', 'nombre' => 'ESENCIA TRES LECHES', 'descripcion' => 'ESENCIA TRES LECHES', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00346', 'nombre' => 'PECTINA TIPO 2', 'descripcion' => 'PECTINA LM-106', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00350', 'nombre' => 'HARINA INSTANTANEA DE AMARANTO', 'descripcion' => 'HARINA INSTANTANEA DE AMARANTO', 'categoria' => 'HARINAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00351', 'nombre' => 'HARINA INSTANTANEA DE QUINUA', 'descripcion' => 'HARINA INSTANTANEA DE QUINUA', 'categoria' => 'HARINAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00352', 'nombre' => 'ESENCIA NARANJA TIPO 6', 'descripcion' => 'ESENCIA NARANJA 5085', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00353', 'nombre' => 'ESENCIA NARANJA TIPO 7', 'descripcion' => 'ESENCIA NARANJA 84196B', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00354', 'nombre' => 'GOMA GUAR', 'descripcion' => 'GOMA GUAR', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00355', 'nombre' => 'ESENCIA VAINILLA TIPO 6', 'descripcion' => 'ESENCIA VAINILLA TIPO 6', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00356', 'nombre' => 'ESENCIA PAPAYA TIPO 1', 'descripcion' => 'ESENCIA PAPAYA 368307', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00357', 'nombre' => 'ESENCIA VAINILLA TIPO 7', 'descripcion' => 'ESENCIA VAINILLA H-3128', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00363', 'nombre' => 'LECHE EN POLVO TIPO 6', 'descripcion' => 'LECHE EN POLVO TIPO 6', 'categoria' => 'SUSTITUTO LACTEO', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00364', 'nombre' => 'VITAMINA A TIPO 2', 'descripcion' => 'VITAMINA A TIPO 2 ACETATO', 'categoria' => 'FORTIFICANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00365', 'nombre' => 'ESENCIA UVA TIPO 2', 'descripcion' => 'ESENCIA UVA FU843-00', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00368', 'nombre' => 'ESENCIA CEREZA', 'descripcion' => 'ESENCIA CEREZA 85021402A', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00369', 'nombre' => 'MEZCLA CLAVO DE OLOR Y CANELA EN POLVO', 'descripcion' => 'MEZCLA CLAVO DE OLOR Y CANELA EN POLVO', 'categoria' => 'ADITIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00374', 'nombre' => 'ESENCIA PLATANO PI7233-00', 'descripcion' => 'ESENCIA PLATANO PI7233-00', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00377', 'nombre' => 'ESENCIA MELON 800150-77', 'descripcion' => 'ESENCIA MELON 800150-77', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00378', 'nombre' => 'ESENCIA FRUTILLA 800854-77', 'descripcion' => 'ESENCIA FRUTILLA 800854-77', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00381', 'nombre' => 'NECTAR CONCENTRADO DE ASAI', 'descripcion' => 'NECTAR CONCENTRADO DE ASAI', 'categoria' => 'PULPAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00382', 'nombre' => 'AROMA NATURAL POMELO ROSADO', 'descripcion' => 'AROMA NATURAL POMELO ROSADO', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00385', 'nombre' => 'CHOCOLITAS CRICK', 'descripcion' => 'CHOCOLITAS CRICK', 'categoria' => 'CEREALES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00386', 'nombre' => 'SABORIZANTE MELON EN POLVO', 'descripcion' => 'SABORIZANTE MELON EN POLVO', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00387', 'nombre' => 'ESENCIA FRUTILLA HB', 'descripcion' => 'ESENCIA FRUTILLA HB', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00390', 'nombre' => 'ESENCIA PIÑA TIPO 4', 'descripcion' => 'ESENCIA PIÑA TIPO 4', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00391', 'nombre' => 'ESENCIA DURAZNO TIPO 7', 'descripcion' => 'ESENCIA DURAZNO TIPO 7', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00394', 'nombre' => 'ESENCIA MANZANA TIPO 3', 'descripcion' => 'MANZANA 11AC 4419 TIPO 3', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00395', 'nombre' => 'ESENCIA FRESA TIPO 3', 'descripcion' => 'FRESA 11AC 4372 TIPO 3', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00396', 'nombre' => 'CARRAGENINA TIPO 2', 'descripcion' => 'CARRAGENINA TIPO 2', 'categoria' => 'ESTABILIZANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00397', 'nombre' => 'ESENCIA COCO TIPO 3', 'descripcion' => 'ESENCIA COCO HB 02-FC7857-00', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00407', 'nombre' => 'CULTIVO LACTEO TIPO 11', 'descripcion' => 'DVS YF-L904 X 50U', 'categoria' => 'CULTIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00421', 'nombre' => 'VITAMINA D', 'descripcion' => 'VITAMINA D', 'categoria' => 'FORTIFICANTES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00423', 'nombre' => 'SABORIZANTE PERA TIPO 1', 'descripcion' => 'SABORIZANTE PERA TIPO 1-5134', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00424', 'nombre' => 'SABORIZANTE PERA TIPO 2', 'descripcion' => 'SABORIZANTE PERA TIPO 2 -33258', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00426', 'nombre' => 'CEREAL HOJUELITA', 'descripcion' => 'CEREAL HOJUELITA', 'categoria' => 'CEREALES', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00428', 'nombre' => 'NECTAR CONCENTRADO DE ACEROLA', 'descripcion' => 'NECTAR CONCENTRADO DE ACEROLA', 'categoria' => 'PULPAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00431', 'nombre' => 'ESENCIA CAMU CAMU TIPO1', 'descripcion' => 'ESENCIA CAMU CAMU TIPO1', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'MP00432', 'nombre' => 'AROMA DE ASSAI TIPO 1', 'descripcion' => 'AROMA DE ASSAI TIPO 1', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00433', 'nombre' => 'PULPA DE ASAI', 'descripcion' => 'PULPA DE ASAI', 'categoria' => 'PULPAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00439', 'nombre' => 'ESENCIA LIMON TIPO 4', 'descripcion' => 'ESENCIA LIMON TIPO 4', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00440', 'nombre' => 'PULPA DE COPOAZU', 'descripcion' => 'PULPA DE COPOAZU', 'categoria' => 'PULPAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00441', 'nombre' => 'ESENCIA POMELO TIPO2', 'descripcion' => 'ESENCIA POMELO TIPO 2', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00443', 'nombre' => 'ESENCIA POMELO TIPO 3', 'descripcion' => 'ESENCIA POMELO TIPO 3', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00445', 'nombre' => 'SABORIZANTE FRAMBUESA TIPO 2', 'descripcion' => 'SABORIZANTE FRAMBUESA TIPO 2', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00447', 'nombre' => 'ESENCIA MANDARINA TIPO2', 'descripcion' => 'ESENCIA MANDARINA TIPO2', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00448', 'nombre' => 'ESENCIA LIMÓN TIPO 5', 'descripcion' => 'ESENCIA LIMÓN TIPO 5', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00449', 'nombre' => 'CULTIVO LACTEO TIPO12', 'descripcion' => 'CULTIVO LACTEO TIPO 12', 'categoria' => 'CULTIVOS', 'unidad' => 'Unidad'],
            ['codigo' => 'MP00451', 'nombre' => 'ESENCIA CHOCOLATE TIPO 4', 'descripcion' => 'ESENCIA CHOCOLATE TIPO 4', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00452', 'nombre' => 'ESENCIA CARAMELO TIPO 2', 'descripcion' => 'ESENCIA CARAMELO TIPO 2', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00453', 'nombre' => 'FOSFATO DISODICO', 'descripcion' => 'FOSFATO DISODICO', 'categoria' => 'REGULADORES DE ACIDEZ', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00455', 'nombre' => 'ESENCIA LECHE TIPO 2', 'descripcion' => 'ESENCIA LECHE TIPO 2', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00456', 'nombre' => 'HARINA INSTANTANEA WILLCAPARU', 'descripcion' => 'HARINA INSTANTANEA WILLCAPARU', 'categoria' => 'HARINAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00458', 'nombre' => 'SABORIZANTE MANZANA Y CEREZA', 'descripcion' => 'SABORIZANTE MANZANA Y CEREZA', 'categoria' => 'ESENCIAS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00460', 'nombre' => 'CULTIVO LACTEOS TIPO 13', 'descripcion' => 'CULTIVO LYOFAST MIX 432 EN 10UC', 'categoria' => 'CULTIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00470', 'nombre' => 'COCOA ALCALINA CHINA', 'descripcion' => 'COCOA ALCALINA CHINA', 'categoria' => 'ADITIVOS', 'unidad' => 'Mililitros'],
            ['codigo' => 'MP00471', 'nombre' => 'CULTIVO TIPO 14', 'descripcion' => 'CULTIVO YOMILD 1.1. 10UC', 'categoria' => 'CULTIVOS', 'unidad' => 'Unidad'],
            ['codigo' => 'EN00007', 'nombre' => 'ASA BOTELLA 2-2,5L', 'descripcion' => 'ASA BOTELLA 2-2,5L', 'categoria' => 'ENVASES', 'unidad' => 'Unidad'],
            ['codigo' => 'EN00241', 'nombre' => 'BOBINA LECHE KREAM NATURAL 946ML 5,80 BS 32X100µ', 'descripcion' => 'BOBINA LECHE KREAM NATURAL 946ML 5,80 BS 32X100µ', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00257', 'nombre' => 'BOBINA LECHE KREAM AVENA PLUS CON COLAGENO 800ML 32X100µ', 'descripcion' => 'BOBINA LECHE KREAM AVENA PLUS CON COLAGENO 800ML 32X100µ', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00296', 'nombre' => 'VASO BLANCO 120ML', 'descripcion' => 'VASO BLANCO 120ML', 'categoria' => 'ENVASES', 'unidad' => 'Unidad'],
            ['codigo' => 'EN00334', 'nombre' => 'TAPA BOTELLA 2L', 'descripcion' => 'TAPA BOTELLA 2L', 'categoria' => 'ENVASES', 'unidad' => 'Unidad'],
            ['codigo' => 'EN00497', 'nombre' => 'BOBINA POWER FRUTT FRUTILLA 200ML 32X80u', 'descripcion' => 'BOBINA POWER FRUTT FRUTILLA 200ML 32X80u', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00504', 'nombre' => 'BOLSA LECHE BX22 25X52X30u', 'descripcion' => 'BOLSA LECHE BX22 25X52X30u', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00544', 'nombre' => 'BOBINA 31X65U LIMONCITO 110ML', 'descripcion' => 'BOBINA 31X65U LIMONCITO 110ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00548', 'nombre' => 'BOLSA GENERICA LECHE 21X36X35U', 'descripcion' => 'BOLSA GENERICA LECHE 21X36X35U', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00554', 'nombre' => 'BOBINA 32X100U LECHE KREAM DESLACTOSADA 800ML', 'descripcion' => 'BOBINA 32X100U LECHE KREAM DESLACTOSADA 800ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00592', 'nombre' => 'BOBINA BLANCA 670MM', 'descripcion' => 'BOBINA BLANCA 670MM', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00594', 'nombre' => 'BOBINA BLANCA 650MM', 'descripcion' => 'BOBINA BLANCA 650MM', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00676', 'nombre' => 'BOLSA NARANJITO 100ML 21X42X30µ', 'descripcion' => 'BOLSA NARANJITO 100ML 21X42X30µ', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00684', 'nombre' => 'BOBINA YOGUSTAR UVA MORA 60ML 31.5X75u', 'descripcion' => 'BOBINA YOGUSTAR UVA MORA 60ML 31.5X75u', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00685', 'nombre' => 'BOBINA YOGUSTAR FRUTILLA FRANBUESA 60ML 31.5X75u', 'descripcion' => 'BOBINA YOGUSTAR FRUTILLA FRANBUESA 60ML 31.5X75u', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00727', 'nombre' => 'BOBINA BEETFRUT DURAZNO 120ML 31X75u', 'descripcion' => 'BOBINA BEETFRUT DURAZNO 120ML 31X75u', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00728', 'nombre' => 'BOBINA BEETFRUT MANZANA 120ML 31X75u', 'descripcion' => 'BOBINA BEETFRUT MANZANA 120ML 31X75u', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00729', 'nombre' => 'BOBINA BEETFRUT PIÑA 120ML 31X75u', 'descripcion' => 'BOBINA BEETFRUT PIÑA 120ML 31X75u', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00744', 'nombre' => 'BOBINA KREAM LIMONELO PRO DE 200ML', 'descripcion' => 'BOBINA KREAM LIMONELO PRO DE 200ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00764', 'nombre' => 'BOB.NECTAR DURAZNO 32X80u 130ML', 'descripcion' => 'BOB.NECTAR DURAZNO 32X80u 130ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00765', 'nombre' => 'BOB.NECTAR MANZANA 32X80u 130ML', 'descripcion' => 'BOB.NECTAR MANZANA 32X80u 130ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00787', 'nombre' => 'BOBINA DE EMPAQUE 45cmX45u', 'descripcion' => 'BOBINA DE EMPAQUE 45cmX45u', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00789', 'nombre' => 'BOTELLA PET 250cc', 'descripcion' => 'BOTELLA PET 250cc', 'categoria' => 'ENVASES', 'unidad' => 'Unidad'],
            ['codigo' => 'EN00796', 'nombre' => 'BOB. HORCHATA DE COCO 110 ML(EL ALTO)', 'descripcion' => 'BOB. HORCHATA DE COCO 110 ML(EL ALTO)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00798', 'nombre' => 'BOB. LECHE CON AVENA 120ML(LA PAZ)', 'descripcion' => 'BOB. LECHE CON AVENA 120ML(LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00799', 'nombre' => 'BOB. LECHE CHOCOLATADA 120ML(LA PAZ)', 'descripcion' => 'BOB. LECHE CHOCOLATADA 120ML(LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00800', 'nombre' => 'BOB. LECHE SABORIZADA 120ML(LA PAZ)', 'descripcion' => 'BOB. LECHE SABORIZADA 120ML(LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00801', 'nombre' => 'BOB. LICUADO DE LECHE CON PULPA DE FRUTAS 120ML(LA PAZ)', 'descripcion' => 'BOB. LICUADO DE LECHE CON PULPA DE FRUTAS 120ML(LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00802', 'nombre' => 'BOB. BEBID LÁCTEA 120ML(LA PAZ)', 'descripcion' => 'BOB. BEBID LÁCTEA 120ML(LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00803', 'nombre' => 'BOB. YOGURT PROBIOTICO 120ML(LA PAZ)', 'descripcion' => 'BOB. YOGURT PROBIOTICO 120ML(LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00804', 'nombre' => 'BOB. YOGURT BEBIBLE CON PULPA DE FRUTAS 120ML(LA PAZ)', 'descripcion' => 'BOB. YOGURT BEBIBLE CON PULPA DE FRUTAS 120ML(LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00805', 'nombre' => 'BOB. NECTAR CON FRUTOS AMAZONICOS 120ML(LA PAZ)', 'descripcion' => 'BOB. NECTAR CON FRUTOS AMAZONICOS 120ML(LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00806', 'nombre' => 'BOB. NECTAR CON FRUTOS AMAZONICOS 150ML(LA PAZ)', 'descripcion' => 'BOB. NECTAR CON FRUTOS AMAZONICOS 150ML(LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00807', 'nombre' => 'BOB. NECTAR CON PULPA DE FRUTAS 120ML(LA PAZ)', 'descripcion' => 'BOB. NECTAR CON PULPA DE FRUTAS 120ML(LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00808', 'nombre' => 'BOB. NECTAR CON PULPA DE FRUTAS 150ML(LA PAZ', 'descripcion' => 'BOB. NECTAR CON PULPA DE FRUTAS 150ML(LA PAZ', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00809', 'nombre' => 'BOB.NECTAR DE FRUTA CITRICAS 120ml (LA PAZ)', 'descripcion' => 'BOB.NECTAR DE FRUTA CITRICAS 120ml (LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00810', 'nombre' => 'BOB.NECTAR DE FRUTA CITRICAS 150ml (LA PAZ)', 'descripcion' => 'BOB.NECTAR DE FRUTA CITRICAS 150ml (LA PAZ)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00811', 'nombre' => 'BOB.NECTAR C/PULPA DE FRUTAS Y CEREALES ANDINOS 120ml LA PAZ', 'descripcion' => 'BOB.NECTAR C/PULPA DE FRUTAS Y CEREALES ANDINOS 120ml LA PAZ', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00812', 'nombre' => 'BOB.NECTAR C/PULPA DE FRUTAS Y CEREALES ANDINOS 150ml LA PAZ', 'descripcion' => 'BOB.NECTAR C/PULPA DE FRUTAS Y CEREALES ANDINOS 150ml LA PAZ', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00814', 'nombre' => 'BOLSA PLASTICA 21X36X35u VERDE PRIMARIA LPZ', 'descripcion' => 'BOLSA PLASTICA 21X36X35u VERDE PRIMARIA LPZ', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00815', 'nombre' => 'BOLSA PLASTICA 21X36X35u ROJO SECUNDARIA LPZ', 'descripcion' => 'BOLSA PLASTICA 21X36X35u ROJO SECUNDARIA LPZ', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00822', 'nombre' => 'ETIQUETA NECTAR DE MANZANA CON QUINUA 250ml (LA PAZ )', 'descripcion' => 'ETIQUETA NECTAR DE MANZANA CON QUINUA 250ml (LA PAZ )', 'categoria' => 'ENVASES', 'unidad' => 'Unidad'],
            ['codigo' => 'EN00837', 'nombre' => 'BOBINA ALIMENTO BEBIBLE DE SOYA SABORIZADO 120ML - ORURO', 'descripcion' => 'BOBINA ALIMENTO BEBIBLE DE SOYA SABORIZADO 120ML - ORURO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00838', 'nombre' => 'BOBINA LECHE CON AVENA 120ML - ORURO', 'descripcion' => 'BOBINA LECHE CON AVENA 120ML - ORURO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00839', 'nombre' => 'BOBINA LECHE CHOCOLATADA 120ML -ORURO', 'descripcion' => 'BOBINA LECHE CHOCOLATADA 120ML -ORURO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00840', 'nombre' => 'BOBINA LECHE SABORIZADA 120ML -ORURO', 'descripcion' => 'BOBINA LECHE SABORIZADA 120ML -ORURO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00841', 'nombre' => 'BOBINA LECHE CON MANZANA Y QUINUA 120ML - ORURO', 'descripcion' => 'BOBINA LECHE CON MANZANA Y QUINUA 120ML - ORURO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00848', 'nombre' => 'BOBINA CRISTAL 31X75u SIN IMPRESION', 'descripcion' => 'BOBINA CRISTAL 31X75u SIN IMPRESION', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00878', 'nombre' => 'BOBINA LECHE KREAM CHOCOLATADA 110ML', 'descripcion' => 'BOBINA LECHE KREAM CHOCOLATADA 110ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00879', 'nombre' => 'BOBINA LECHE KREAM CHIRIMOYA 110ML', 'descripcion' => 'BOBINA LECHE KREAM CHIRIMOYA 110ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00880', 'nombre' => 'BOBINA LECHE KREAM PLATANO 110ML', 'descripcion' => 'BOBINA LECHE KREAM PLATANO 110ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00883', 'nombre' => 'BOBINA LECHE KREAM MORA 110ML', 'descripcion' => 'BOBINA LECHE KREAM MORA 110ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00884', 'nombre' => 'BOBINA LECHE KREAM COCO 110ML', 'descripcion' => 'BOBINA LECHE KREAM COCO 110ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00888', 'nombre' => 'BOBINA KREAM LECHE AVENA 110ML', 'descripcion' => 'BOBINA KREAM LECHE AVENA 110ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00889', 'nombre' => 'BOB.KREAM POWER FRUTT MANZANA 180ML', 'descripcion' => 'BOB.KREAM POWER FRUTT MANZANA 180ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00890', 'nombre' => 'BOB.KREAM POWER FRUTT DURAZNO 180ML', 'descripcion' => 'BOB.KREAM POWER FRUTT DURAZNO 180ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00912', 'nombre' => 'BOBINA KREAM NARANJITO PRO 90ML', 'descripcion' => 'BOBINA KREAM NARANJITO PRO 90ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00914', 'nombre' => 'BOB. 32X75u LECHE C/QUINUA Y MANZANA 150ML - SACABA', 'descripcion' => 'BOB. 32X75u LECHE C/QUINUA Y MANZANA 150ML - SACABA', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00915', 'nombre' => 'BOB. 32X75u LECHE CON AVENA 160ML - SACABA', 'descripcion' => 'BOB. 32X75u LECHE CON AVENA 160ML - SACABA', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00916', 'nombre' => 'BOB. 32X75u LECHE CON CEREAL ARROZ 150ML -SACABA', 'descripcion' => 'BOB. 32X75u LECHE CON CEREAL ARROZ 150ML -SACABA', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00917', 'nombre' => 'BOB. 32X75u LECHE CHOCOLATADA C/ HARINA DE CEREAL AMARANTO 150ML -SACABA', 'descripcion' => 'BOB. 32X75u LECHE CHOCOLATADA C/ HARINA DE CEREAL AMARANTO 150ML -SACABA', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00918', 'nombre' => 'BOBINA 31X75u NECTAR DE FRUTA TROPICAL 160ML -SACABA', 'descripcion' => 'BOBINA 31X75u NECTAR DE FRUTA TROPICAL 160ML -SACABA', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00920', 'nombre' => 'BOB. 31X75u BEBIDA LÁCTEA C/ CEREAL Y COLAGENO 120ML- EL ALTO', 'descripcion' => 'BOB. 31X75u BEBIDA LÁCTEA C/ CEREAL Y COLAGENO 120ML- EL ALTO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00921', 'nombre' => 'BOB. 31X75u NECTAR DE FRUTA Y VERDURA 120ML - EL ALTO', 'descripcion' => 'BOB. 31X75u NECTAR DE FRUTA Y VERDURA 120ML - EL ALTO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00922', 'nombre' => 'BOBINA 32X75u LECHE CON WILLKAPARU 110ML - EL ALTO', 'descripcion' => 'BOBINA 32X75u LECHE CON WILLKAPARU 110ML - EL ALTO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00923', 'nombre' => 'BOBINA 32X75u LECHE SABORIZADA CON CEREAL 110ML - EL ALTO', 'descripcion' => 'BOBINA 32X75u LECHE SABORIZADA CON CEREAL 110ML - EL ALTO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00924', 'nombre' => 'BOBINA 32X75u ALIMENTO BEBIBLE A BASE DE EXTRACTO DE SOYA CON LECHE DE VACA Y CEREALES 110ML - E', 'descripcion' => 'BOBINA 32X75u ALIMENTO BEBIBLE A BASE DE EXTRACTO DE SOYA CON LECHE DE VACA Y CEREALES 110ML - E', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00925', 'nombre' => 'BOBINA 32X75u ALIMENTO BEBIBLE A BASE DE EXTRACTO DE SOYA CON LECHE DE VACA Y PULPA DE FRUTA 1', 'descripcion' => 'BOBINA 32X75u ALIMENTO BEBIBLE A BASE DE EXTRACTO DE SOYA CON LECHE DE VACA Y PULPA DE FRUTA 1', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00926', 'nombre' => 'BOBINA 32X75u ALIMENTO BEBIBLE A BASE DE EXRACTO DE SOYA CON PULPA DE FRUTA 110ML - EL ALTO', 'descripcion' => 'BOBINA 32X75u ALIMENTO BEBIBLE A BASE DE EXRACTO DE SOYA CON PULPA DE FRUTA 110ML - EL ALTO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00927', 'nombre' => 'BOBINA 32X75u ALIMENTO BEBIBLE DE SOYA CON CEREALES 110ML - EL ALTO', 'descripcion' => 'BOBINA 32X75u ALIMENTO BEBIBLE DE SOYA CON CEREALES 110ML - EL ALTO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00928', 'nombre' => 'BOBINA 32X75u ALIMENTO BEBIBLE DE SOYA SABORIZADA 110ML - EL ALTO', 'descripcion' => 'BOBINA 32X75u ALIMENTO BEBIBLE DE SOYA SABORIZADA 110ML - EL ALTO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00937', 'nombre' => 'BOB.LECHE C/MANZANA Y QUINUA 110ML EL ALTO', 'descripcion' => 'BOB.LECHE C/MANZANA Y QUINUA 110ML EL ALTO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00938', 'nombre' => 'BOBINA JUGO 100ML -ORURO', 'descripcion' => 'BOBINA JUGO 100ML -ORURO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00939', 'nombre' => 'BOBINA YOGURT 100ML - ORURO', 'descripcion' => 'BOBINA YOGURT 100ML - ORURO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00940', 'nombre' => 'BOBINA BEBIDA LÁCTEA 100ML - ORURO', 'descripcion' => 'BOBINA BEBIDA LÁCTEA 100ML - ORURO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00941', 'nombre' => 'BOBINA JUGO LÁCTEO 100ML - ORURO', 'descripcion' => 'BOBINA JUGO LÁCTEO 100ML - ORURO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00944', 'nombre' => 'BOBINA KREAM LOLA 900ML', 'descripcion' => 'BOBINA KREAM LOLA 900ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00952', 'nombre' => 'BOB.KREAM TORONJITO PRO 90ML', 'descripcion' => 'BOB.KREAM TORONJITO PRO 90ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00956', 'nombre' => 'ETIQUETA YOGURT FRUTADO SACABA 90G', 'descripcion' => 'ETIQUETA YOGURT FRUTADO SACABA 90G', 'categoria' => 'ENVASES', 'unidad' => 'Unidad'],
            ['codigo' => 'EN00963', 'nombre' => 'BOBINA LECHE KREAM FRUTILLA 110 ML', 'descripcion' => 'BOBINA LECHE KREAM FRUTILLA 110 ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00964', 'nombre' => 'BOBINA LECHE KREAM ENRIQUECIDA 800 ML', 'descripcion' => 'BOBINA LECHE KREAM ENRIQUECIDA 800 ML', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00291', 'nombre' => 'BOTELLA 2 L', 'descripcion' => 'BOTELLA 2 LITROS', 'categoria' => 'ENVASES', 'unidad' => 'Unidad'],
            ['codigo' => 'MP00473', 'nombre' => 'SABORIZANTE DURAZNO PD671-46 EN POLVO', 'descripcion' => 'SABORIZANTE DURAZNO PD671-46 EN POLVO', 'categoria' => 'ESENCIAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00021', 'nombre' => 'WHITE CLEAN K3', 'descripcion' => 'WHITE CLEAN K3', 'categoria' => 'DETERGENTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00023', 'nombre' => 'SANIT 10 PLUS', 'descripcion' => 'SANIT 10 PLUS', 'categoria' => 'DETERGENTES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00004', 'nombre' => 'PEROXIDO DE HIDROGENO', 'descripcion' => 'PEROXIDO DE HIDROGENO', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00056', 'nombre' => 'TERMOCONTRAIBLE 43X54.5X80', 'descripcion' => 'TERMOCONTRAIBLE 43X54.5X80', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00006', 'nombre' => 'WETBOIL 101', 'descripcion' => 'WETBOIL 101', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00008', 'nombre' => 'WETBOIL 402', 'descripcion' => 'WETBOIL 402', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00009', 'nombre' => 'WETBOIL 801', 'descripcion' => 'WETBOIL 801', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL0003', 'nombre' => 'HIPOCLORITO DE SODIO', 'descripcion' => 'HIPOCLORITO DE SODIO', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00015', 'nombre' => 'ALCOHOL 96%', 'descripcion' => 'ALCOHOL 96%', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Litro'],
            ['codigo' => 'EN00959', 'nombre' => 'BOBINA 31X75ALIMENTO COMPLEMENTARIO NECTAR CON FRUTAS', 'descripcion' => 'ALIMENTO COMPLEMENTARIO NECTAR CON FRUTAS', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00951', 'nombre' => 'BOBINA 32X75u ALIM ENTO COMPLEMENTARIO NECTAR CON FRUTAS', 'descripcion' => 'BOBINA 32X75u ALIMENTO COMPLEMENTARIO NECTAR CON FRUTAS', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00973', 'nombre' => 'BOBINA BEETFRUT MANZANA 100 ml 31x75u', 'descripcion' => 'BOBINA BEETFRUT MANZANA 100 ml 31x75u', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00975', 'nombre' => 'BOBINA BEETFRUT PIÑA 100 ml 31x75u', 'descripcion' => 'BOBINA BEETFRUT PIÑA 100 ml 31x75u', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00974', 'nombre' => 'BOBINA BEETFRUT DURAZNO 100 ml 31x75u', 'descripcion' => 'BOBINA BEETFRUT DURAZNO 100 ml 31x75u', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00976', 'nombre' => 'BOBINA KREAM NARANJITO PRO 80 ml', 'descripcion' => 'BOBINA KREAM NARANJITO PRO 80 ml', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00001', 'nombre' => 'SODA CAUSTICA', 'descripcion' => 'SODA CAUSTICA', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00214', 'nombre' => 'ETIQUETA BD IMPRESA YOGURT CHIRIMOYA 2 LITROS', 'descripcion' => 'ETIQUETA BD IMPRESA YOGURT CHIRIMOYA 2 LITROS', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00012', 'nombre' => 'FLOCULANTE IONICO ANIONICO DAF-135', 'descripcion' => 'FLOCULANTE IONICO ANIONICO DAF-135', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00019', 'nombre' => 'FLOCULANTE CATIONICO IONICO DAF-168', 'descripcion' => 'FLOCULANTE CATIONICO IONICO DAF-168', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00020', 'nombre' => 'COAGULANTE DAF-A30', 'descripcion' => 'COAGULANTE DAF-A30', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00947', 'nombre' => 'BOBINA 32X75u ALIMENTO COMPLEMENTARIO ESCOLAR LECHE SABORIZADA CON CEREAL (GENERICO)', 'descripcion' => 'BOBINA 32X75u ALIMENTO COMPLEMENTARIO ESCOLAR LECHE SABORIZADA CON CEREAL (GENERICO)', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL000018', 'nombre' => 'ÁCIDO PARACETICO', 'descripcion' => 'ÁCIDO PARACETICO', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'SL00007', 'nombre' => 'WETBOIL 201', 'descripcion' => 'WETBOIL 201', 'categoria' => 'SUSTANCIAS QUÍMICAS', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00950', 'nombre' => 'BOBINA ALIMENTO COMPLEMENTARIO ESCOLAR BEBIDA LACTEA (GENERICO)31.X75', 'descripcion' => 'BOBINA ALIMENTO COMPLEMENTARIO ESCOLAR BEBIDA LACTEA (GENERICO)32.5X75', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00949', 'nombre' => 'BOBINA ALIMENTO COMPLEMENTARIO ESCOLAR JUGO CON PULPA DE FRUTAS (GENERICO)31.5X75', 'descripcion' => 'BOBINA ALIMENTO COMPLEMENTARIO ESCOLAR JUGO CON PULPA DE FRUTAS (GENERICO)31.5X75', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00985', 'nombre' => 'BOBINA ALIMENTO COMPLEMENTARIO YOGURT (GENERICO)31X75 U', 'descripcion' => 'BOBINA ALIMENTO COMPLEMENTARIO YOGURT (GENERICO)31X75 U', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00212', 'nombre' => 'ETIQUETA BD IMPRESA YOGURT DURAZNO', 'descripcion' => 'ETIQUETA BD IMPRESA YOGURT FRUTILLA 2 LITROS', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00221', 'nombre' => 'ETIQUETA BD IMPRESA YOGURT MANGO', 'descripcion' => 'ETIQUETA BD IMPRESA YOGURT MANGO', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00218', 'nombre' => 'ETIQUETA BD IMPRESA YOGURT BERRIES', 'descripcion' => 'ETIQUETA BD IMPRESA YOGURT BERRIES', 'categoria' => 'ENVASES', 'unidad' => 'Unidad'],
            ['codigo' => 'EN00979', 'nombre' => 'ETIQUETA BD IMPRESA YOGURT MARACUYA', 'descripcion' => 'ETIQUETA BD IMPRESA YOGURT MARACUYA', 'categoria' => 'ENVASES', 'unidad' => 'Unidad'],
            ['codigo' => 'EN00280', 'nombre' => 'ETIQUETA BD IMPRESA YOGURT PIÑA', 'descripcion' => 'ETIQUETA BD IMPRESA YOGURT PIÑA', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00478', 'nombre' => 'ETIQUETA BD IMPRESA YOGURT MANZANA', 'descripcion' => 'ETIQUETA BD IMPRESA YOGURT MANZANA', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
            ['codigo' => 'EN00057', 'nombre' => 'TERMOCONTRAIBLE 35X45X80', 'descripcion' => 'TERMOCONTRAIBLE 35X45X80', 'categoria' => 'ENVASES', 'unidad' => 'Kilogramo'],
        ];

        foreach ($materiasPrimas as $materia) {
            DB::table('PLL_item_materia_primas')->insert([
                'codigo' => $materia['codigo'],
                'nombre' => $materia['nombre'],
                'descripcion' => $materia['descripcion'],
                'categoria_materia_prima_id' => $this->categorias[$materia['categoria']],
                'unidad_id' => $this->unidades[$materia['unidad']],
                'ubicacion_id' => 1,
                'organoleptica' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
