<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MantenimientoSeeder4 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('MAN_repuestos')->insert([
            ['codigo' =>    4243, 'nombre' => '	5F25004243 Thermostat Electrovac	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (B4) 	', 'stock_minimo' =>    1, 'precio_relativo' =>    25.00],
            ['codigo' =>    296043, 'nombre' => '	4296043 Dairi Nut	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (B4) 	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.00],
            ['codigo' =>    300084, 'nombre' => '	4280281 O-ring 28 	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (F7)	', 'stock_minimo' =>    2, 'precio_relativo' =>    15.65],
            ['codigo' =>    300087, 'nombre' => '	4296621 Gasket 38 Clamp	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (C12)	', 'stock_minimo' =>    18, 'precio_relativo' =>    80.80],
            ['codigo' =>    800956, 'nombre' => '	Sello Mecanico 25mm tg/sil/vi g60 MG1	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    2, 'precio_relativo' =>    326.90],
            ['codigo' =>    800769, 'nombre' => '	Sello Mecanico 28mm car/cer/epdm tipo21	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    1, 'precio_relativo' =>    82.10],
            ['codigo' =>    802392, 'nombre' => '	Sello Mecanico 18mm TipoM cer/car/ni	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    1, 'precio_relativo' =>    63.00],
            ['codigo' =>    802854, 'nombre' => '	Sello Mecanico 20mm ce/ca/ni	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    1, 'precio_relativo' =>    80.00],
            ['codigo' =>    983036, 'nombre' => '	Sello Mecanico P/Bomba SOYA	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    1, 'precio_relativo' =>    762.18],
            ['codigo' =>    983253, 'nombre' => '	Sello Mecanico 16mm	', 'descripcion' =>    NULL, 'observacion' => '	No Corresponde Soya	pza (E-A5)	', 'stock_minimo' =>    6, 'precio_relativo' =>    1.00],
            ['codigo' =>    800901, 'nombre' => '	Sello Mecanico EB18.0200.BVFF 749	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    1, 'precio_relativo' =>    170.20],
            ['codigo' =>    800919, 'nombre' => '	Sello Mecanico 92B 0320 CRSBEB 712-32	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    4, 'precio_relativo' =>    1392.00],
            ['codigo' =>    800949, 'nombre' => '	Sello Mecanico D16866 026738005	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.00],
            ['codigo' =>    800900, 'nombre' => '	Sello Mecanico 551B-35 TC/TC/VITON	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.00],
            ['codigo' =>    800926, 'nombre' => '	Sello Mecanico FC55.0222VV 356002104	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    1, 'precio_relativo' =>    170.18],
            ['codigo' =>    983250, 'nombre' => '	Sello Mecanico Para Bomba 25mm SOYA	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    3, 'precio_relativo' =>    1168.50],
            ['codigo' =>    800967, 'nombre' => '	Sello Mecanico CS3.0180 CER/CAR/EPDM	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    2, 'precio_relativo' =>    250.00],
            ['codigo' =>    800966, 'nombre' => '	Sello Mecanico STK RD11.033.QVEFF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    1, 'precio_relativo' =>    717.72],
            ['codigo' =>    802855, 'nombre' => '	Sello Mecanico Type 21-30mm CA/CER/EPR	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A5)	', 'stock_minimo' =>    2, 'precio_relativo' =>    120.10],
            ['codigo' =>    800365, 'nombre' => '	Perno Inox Avellanado M4x12	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P1)	', 'stock_minimo' =>    6, 'precio_relativo' =>    0.57],
            ['codigo' =>    800290, 'nombre' => '	Perno Inox Hex M4x16 Rosca Total	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P2)	', 'stock_minimo' =>    11, 'precio_relativo' =>    0.73],
            ['codigo' =>    800218, 'nombre' => '	Perno Hex 1/4x1/2 	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P3)	', 'stock_minimo' =>    38, 'precio_relativo' =>    0.41],
            ['codigo' =>    800530, 'nombre' => '	Perno Inox Hex M8x40	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P6)	', 'stock_minimo' =>    1, 'precio_relativo' =>    2.10],
            ['codigo' =>    800230, 'nombre' => '	Perno Inox Hex 1/4x1/2	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P7)	', 'stock_minimo' =>    12, 'precio_relativo' =>    0.88],
            ['codigo' =>    801624, 'nombre' => '	Tuerca Inox M4 Paso 0.7mm 	', 'descripcion' =>    'AISI 304', 'observacion' => '	Ninguna	pza (P8)	', 'stock_minimo' =>    12, 'precio_relativo' =>    0.59],
            ['codigo' =>    801117, 'nombre' => '	Perno Inox Avellanado Philips M5x10	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P9)	', 'stock_minimo' =>    191, 'precio_relativo' =>    0.71],
            ['codigo' =>    801745, 'nombre' => '	Perno Inox Avellanado Allen M5x16	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P10)	', 'stock_minimo' =>    72, 'precio_relativo' =>    1.12],
            ['codigo' =>    800754, 'nombre' => '	Perno Inox Hex M6x35	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P11)	', 'stock_minimo' =>    2, 'precio_relativo' =>    2.12],
            ['codigo' =>    801687, 'nombre' => '	Perno Inox Hex M6x25	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P12)	', 'stock_minimo' =>    10, 'precio_relativo' =>    1.84],
            ['codigo' =>    801947, 'nombre' => '	Perno Inox Avellanado Allen  M10X20	', 'descripcion' =>    'D7991', 'observacion' => '	Ninguna	pza (P13)	', 'stock_minimo' =>    22, 'precio_relativo' =>    2.57],
            ['codigo' =>    800179, 'nombre' => '	Perno Inox Allen M4x20mm	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P14)	', 'stock_minimo' =>    28, 'precio_relativo' =>    1.17],
            ['codigo' =>    983236, 'nombre' => '	Perno Inox Allen 16	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P15)	', 'stock_minimo' =>    48, 'precio_relativo' =>    10.44],
            ['codigo' =>    800247, 'nombre' => '	Perno Inox Allen 1/4x1 	', 'descripcion' =>    NULL, 'observacion' => '	SOYA	pza (P16)	', 'stock_minimo' =>    55, 'precio_relativo' =>    2.32],
            ['codigo' =>    801948, 'nombre' => '	Perno Inox Cilindrico M3x20	', 'descripcion' =>    'D84', 'observacion' => '	Ninguna	pza (P17)	', 'stock_minimo' =>    14, 'precio_relativo' =>    0.63],
            ['codigo' =>    802790, 'nombre' => '	Tornillo Inox de Encarne DIN7981 4.2x25	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P18)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.77],
            ['codigo' =>    801949, 'nombre' => '	Tornillo Inox de Encarne DIN7981 4.2x32	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P19)	', 'stock_minimo' =>    84, 'precio_relativo' =>    0.88],
            ['codigo' =>    802434, 'nombre' => '	Tornillo Zincado 5x3	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P21)	', 'stock_minimo' =>    25, 'precio_relativo' =>    0.11],
            ['codigo' =>    801106, 'nombre' => '	Perno Conico Cabeza Plana	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P22)	', 'stock_minimo' =>    47, 'precio_relativo' =>    0.71],
            ['codigo' =>    802411, 'nombre' => '	Tornillo Cabeza Arandela 8x3/4	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P23)	', 'stock_minimo' =>    145, 'precio_relativo' =>    0.17],
            ['codigo' =>    800196, 'nombre' => '	Perno Maquina 1/4x1/2	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P24)	', 'stock_minimo' =>    14, 'precio_relativo' =>    0.19],
            ['codigo' =>    800197, 'nombre' => '	Tuerca Inox Hex 1/4 	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P25)	', 'stock_minimo' =>    20, 'precio_relativo' =>    1.21],
            ['codigo' =>    800177, 'nombre' => '	Tuerca Inox Autotrabante M5	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P26)	', 'stock_minimo' =>    38, 'precio_relativo' =>    0.77],
            ['codigo' =>    802267, 'nombre' => '	Tuerca Hex M10 Paso 1.5mm	', 'descripcion' =>    NULL, 'observacion' => '	Negro	pza (P27)	', 'stock_minimo' =>    13, 'precio_relativo' =>    0.50],
            ['codigo' =>    800134, 'nombre' => '	Perno Inox Hex M8x50 Rosca Total	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P28)	', 'stock_minimo' =>    22, 'precio_relativo' =>    3.20],
            ['codigo' =>    801764, 'nombre' => '	Tuerca Inox M16 Paso 2.0mm	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P29)	', 'stock_minimo' =>    9, 'precio_relativo' =>    5.35],
            ['codigo' =>    801757, 'nombre' => '	Tuerca Inox Autotrabante M12	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P30)	', 'stock_minimo' =>    3, 'precio_relativo' =>    2.93],
            ['codigo' =>    801680, 'nombre' => '	Volanda de Presión 5/8	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P31)	', 'stock_minimo' =>    2, 'precio_relativo' =>    0.76],
            ['codigo' =>    801041, 'nombre' => '	Tuerca Inox Mariposa M5	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P32)	', 'stock_minimo' =>    4, 'precio_relativo' =>    2.26],
            ['codigo' =>    801441, 'nombre' => '	Tuerca Inox Hex Autotrabante M8	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P34)	', 'stock_minimo' =>    20, 'precio_relativo' =>    1.70],
            ['codigo' =>    801739, 'nombre' => '	Tuerca Inox Hex Autotrabante M6	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P35)	', 'stock_minimo' =>    40, 'precio_relativo' =>    0.82],
            ['codigo' =>    800188, 'nombre' => '	Perno Maquina 3/16x3/8	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P37)	', 'stock_minimo' =>    68, 'precio_relativo' =>    0.17],
            ['codigo' =>    801420, 'nombre' => '	Tuerca Hex 3/16	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P37)	', 'stock_minimo' =>    78, 'precio_relativo' =>    0.10],
            ['codigo' =>    801754, 'nombre' => '	Tuerca Inox 5/16 Paso 18Hilos	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P38)	', 'stock_minimo' =>    5, 'precio_relativo' =>    1.73],
            ['codigo' =>    801631, 'nombre' => '	Volanda Inox Plana M10	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P39)	', 'stock_minimo' =>    9, 'precio_relativo' =>    0.79],
            ['codigo' =>    801763, 'nombre' => '	Volanda Inox de Presion M5	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P40)	', 'stock_minimo' =>    70, 'precio_relativo' =>    0.23],
            ['codigo' =>    801609, 'nombre' => '	Terminal Punta Hueca 25mm2	', 'descripcion' =>    NULL, 'observacion' => '	Cafe	pza (P41)	', 'stock_minimo' =>    7, 'precio_relativo' =>    0.94],
            ['codigo' =>    800190, 'nombre' => '	Perno Inox Hex M6x30	', 'descripcion' =>    '2 Unidades en Caja de Reposicion', 'observacion' => '	Ninguna	pza (P42)	', 'stock_minimo' =>    7, 'precio_relativo' =>    2.04],
            ['codigo' =>    801652, 'nombre' => '	Volanda Inox de Presion M6	', 'descripcion' =>    'D7980', 'observacion' => '	Ninguna	pza (P43)	', 'stock_minimo' =>    19, 'precio_relativo' =>    0.27],
            ['codigo' =>    802909, 'nombre' => '	Volanda de Presion M6	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P43)	', 'stock_minimo' =>    25, 'precio_relativo' =>    0.27],
            ['codigo' =>    801447, 'nombre' => '	Volanda Inox de Presion M8	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P44)	', 'stock_minimo' =>    5, 'precio_relativo' =>    0.54],
            ['codigo' =>    801630, 'nombre' => '	Volanda Inox de Presion M10	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P45)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.57],
            ['codigo' =>    802285, 'nombre' => '	Volanda Inox de Presion M10	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P46)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.53],
            ['codigo' =>    801625, 'nombre' => '	Volanda Inox Plana M4	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P47)	', 'stock_minimo' =>    124, 'precio_relativo' =>    0.13],
            ['codigo' =>    801741, 'nombre' => '	Volanda Inox Plana M6	', 'descripcion' =>    'D125A PPA1Y12', 'observacion' => '	Ninguna	pza (P48)	', 'stock_minimo' =>    20, 'precio_relativo' =>    0.34],
            ['codigo' =>    802203, 'nombre' => '	Terminal Punta Hueca 16mm2 	', 'descripcion' =>    'KSN E601', 'observacion' => '	Blanco	pza (P49)	', 'stock_minimo' =>    5, 'precio_relativo' =>    0.52],
            ['codigo' =>    802350, 'nombre' => '	Terminal Ojal 4-6mm2 Diam 6.5mm	', 'descripcion' =>    'Ojal Redondo', 'observacion' => '	Amarillo	pza (P52)	', 'stock_minimo' =>    33, 'precio_relativo' =>    0.64],
            ['codigo' =>    800292, 'nombre' => '	Terminal Ojal 16mm Diam 6.2mm	', 'descripcion' =>    '2 Unidades en Caja de Reposicion ', 'observacion' => '	Metal	pza (P53)	', 'stock_minimo' =>    14, 'precio_relativo' =>    1.50],
            ['codigo' =>    800293, 'nombre' => '	Terminal Punta Hueca 4mm2	', 'descripcion' =>    NULL, 'observacion' => '	Gris	pza (P55)	', 'stock_minimo' =>    86, 'precio_relativo' =>    0.31],
            ['codigo' =>    802201, 'nombre' => '	Terminal Tipo Y SVS 2-5	', 'descripcion' =>    '4 unidades caja de repuestos', 'observacion' => '	Azul	pza (P56)	', 'stock_minimo' =>    90, 'precio_relativo' =>    0.28],
            ['codigo' =>    801028, 'nombre' => '	Perno 6x3/8	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (P57)	', 'stock_minimo' =>    40, 'precio_relativo' =>    0.06],
            ['codigo' =>    802204, 'nombre' => '	Terminal Punta Hueca 1.5mm	', 'descripcion' =>    NULL, 'observacion' => '	Amarillo	pza (P58)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.25],
            ['codigo' =>    802200, 'nombre' => '	Terminal Punta Hueca 1.5mm	', 'descripcion' =>    '4 Unidades en Caja de Reposicion', 'observacion' => '	Negro	pza (P60)	', 'stock_minimo' =>    239, 'precio_relativo' =>    0.13],
            ['codigo' =>    802869, 'nombre' => '	Terminal Ojal 1.25-4	', 'descripcion' =>    NULL, 'observacion' => '	Rojo	pza (P61)	', 'stock_minimo' =>    63, 'precio_relativo' =>    0.48],
            ['codigo' =>    802229, 'nombre' => '	Terminal Ojal 4-6mm2 Diam 5.3	', 'descripcion' =>    '4 Unidades en Caja de Reposicion', 'observacion' => '	Ninguna	pza (P62)	', 'stock_minimo' =>    28, 'precio_relativo' =>    0.50],
            ['codigo' =>    800254, 'nombre' => '	Terminal Ojal 10mm2 Diam 6.2mm	', 'descripcion' =>    '2Unidades en Caja de Reposicion', 'observacion' => '	Metal	pza (P63)	', 'stock_minimo' =>    19, 'precio_relativo' =>    1.46],
            ['codigo' =>    800296, 'nombre' => '	Terminal Ojal 1.25-6mm	', 'descripcion' =>    NULL, 'observacion' => '	Rojo	pza (P64)	', 'stock_minimo' =>    31, 'precio_relativo' =>    0.42],
            ['codigo' =>    802895, 'nombre' => '	Terminal Tipo Y 1.5mm  	', 'descripcion' =>    NULL, 'observacion' => '	Rojo	pza (G1)	', 'stock_minimo' =>    0, 'precio_relativo' =>    0.40],
            ['codigo' =>    800244, 'nombre' => '	Perno Inox Hex 5/16x3/4	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G3)	', 'stock_minimo' =>    6, 'precio_relativo' =>    1.61],
            ['codigo' =>    801769, 'nombre' => '	Tirafondo Inox de Encarne M10x30	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G4)	', 'stock_minimo' =>    10, 'precio_relativo' =>    2.87],
            ['codigo' =>    802747, 'nombre' => '	Tuerca Hex Sincado M6	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G5)	', 'stock_minimo' =>    20, 'precio_relativo' =>    0.55],
            ['codigo' =>    802748, 'nombre' => '	Perno Hexa Sincado M6	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G5)	', 'stock_minimo' =>    1, 'precio_relativo' =>    1.20],
            ['codigo' =>    800371, 'nombre' => '	Perno Inox Allen M6x20mm	', 'descripcion' =>    'Cilindrica', 'observacion' => '	Ninguna	pza (G6)	', 'stock_minimo' =>    8, 'precio_relativo' =>    1.23],
            ['codigo' =>    802691, 'nombre' => '	Perno Inox Hex M8x30	', 'descripcion' =>    'Rosca Total', 'observacion' => '	Ninguna	pza (G7)	', 'stock_minimo' =>    39, 'precio_relativo' =>    2.26],
            ['codigo' =>    800255, 'nombre' => '	Perno Inox Allen M8x20mm	', 'descripcion' =>    'Cilindrica', 'observacion' => '	Ninguna	pza (G8)	', 'stock_minimo' =>    7, 'precio_relativo' =>    2.51],
            ['codigo' =>    802647, 'nombre' => '	Terminal Punta Hueca 2.5mm2	', 'descripcion' =>    '4 Unidades en Caja de Reposicion', 'observacion' => '	Azul	pza (G9)	', 'stock_minimo' =>    339, 'precio_relativo' =>    0.27],
            ['codigo' =>    802778, 'nombre' => '	Tuerca Inox Hex M6 3 Hilos	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G10)	', 'stock_minimo' =>    11, 'precio_relativo' =>    0.47],
            ['codigo' =>    801219, 'nombre' => '	Perno Inox Hex M8x60	', 'descripcion' =>    'Rosca Total', 'observacion' => '	Ninguna	pza (G12)	', 'stock_minimo' =>    6, 'precio_relativo' =>    3.69],
            ['codigo' =>    800129, 'nombre' => '	Perno Inox Hex M6x16	', 'descripcion' =>    'Rosca Total', 'observacion' => '	Ninguna	pza (G13)	', 'stock_minimo' =>    6, 'precio_relativo' =>    0.79],
            ['codigo' =>    802830, 'nombre' => '	Perno Inox Allen M6x50	', 'descripcion' =>    'Cilindrica', 'observacion' => '	Ninguna	pza (G15)	', 'stock_minimo' =>    50, 'precio_relativo' =>    2.37],
            ['codigo' =>    800557, 'nombre' => '	Perno Hex M8x16	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G16)	', 'stock_minimo' =>    6, 'precio_relativo' =>    1.13],
            ['codigo' =>    802555, 'nombre' => '	Anillo de Seguridad Eje Ext Din471 E13	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G17)	', 'stock_minimo' =>    18, 'precio_relativo' =>    1.57],
            ['codigo' =>    802841, 'nombre' => '	Anillo de Seguridad Eje Ext E48	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G17)	', 'stock_minimo' =>    2, 'precio_relativo' =>    10.00],
            ['codigo' =>    800337, 'nombre' => '	Rodamiento 6009 NACHI	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    2, 'precio_relativo' =>    119.00],
            ['codigo' =>    800054, 'nombre' => '	Rodamiento 6209-2RS SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    2, 'precio_relativo' =>    231.00],
            ['codigo' =>    800008, 'nombre' => '	Rodamiento 6207-2RS1 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    10, 'precio_relativo' =>    175.00],
            ['codigo' =>    800032, 'nombre' => '	Rodamiento 6008-2RS SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    NULL, 'precio_relativo' =>    150.00],
            ['codigo' =>    800006, 'nombre' => '	Rodamiento 6205-2RSH SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    9, 'precio_relativo' =>    100.00],
            ['codigo' =>    800038, 'nombre' => '	Rodamiento 6008-2Z SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    2, 'precio_relativo' =>    181.00],
            ['codigo' =>    800007, 'nombre' => '	Rodamiento 6206-2RS1 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    10, 'precio_relativo' =>    110.00],
            ['codigo' =>    800024, 'nombre' => '	Rodamiento 6006-2RS SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    3, 'precio_relativo' =>    96.00],
            ['codigo' =>    800022, 'nombre' => '	Rodamiento 6006-2Z SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    1, 'precio_relativo' =>    45.00],
            ['codigo' =>    800004, 'nombre' => '	Rodamiento 6204-2RSH/C3 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    2, 'precio_relativo' =>    95.00],
            ['codigo' =>    800015, 'nombre' => '	Rodamiento 16005 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    16, 'precio_relativo' =>    73.00],
            ['codigo' =>    800003, 'nombre' => '	Rodamiento 6203-2RSH SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    20, 'precio_relativo' =>    78.00],
            ['codigo' =>    800001, 'nombre' => '	Rodamiento 6201	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    18, 'precio_relativo' =>    55.00],
            ['codigo' =>    800013, 'nombre' => '	Rodamiento 6004-2RSH SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    8, 'precio_relativo' =>    85.00],
            ['codigo' =>    800021, 'nombre' => '	Rodamiento 6003-2RSH SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    1, 'precio_relativo' =>    50.00],
            ['codigo' =>    800057, 'nombre' => '	Rodamiento 6000ZZC3-GA2 KOYO	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    4, 'precio_relativo' =>    39.00],
            ['codigo' =>    802713, 'nombre' => '	Rodamiento 6204-DDUC3E NSK	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    2, 'precio_relativo' =>    59.00],
            ['codigo' =>    800002, 'nombre' => '	Rodamiento 6202-2RSH/C3 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    1, 'precio_relativo' =>    68.00],
            ['codigo' =>    800025, 'nombre' => '	Rodamiento 6004 FAG 	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.00],
            ['codigo' =>    800036, 'nombre' => '	Rodamiento 6804-2Z NACHI/NSK	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    3, 'precio_relativo' =>    0.00],
            ['codigo' =>    800552, 'nombre' => '	Rodamiento 6201 NSK	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A1)	', 'stock_minimo' =>    2, 'precio_relativo' =>    45.00],
            ['codigo' =>    800029, 'nombre' => '	Rodamiento UC204D1 NTN/17550	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    21, 'precio_relativo' =>    94.40],
            ['codigo' =>    800028, 'nombre' => '	Rodamiento UCFL204D1 NTN	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    3, 'precio_relativo' =>    120.00],
            ['codigo' =>    800045, 'nombre' => '	Rodamiento UCP204D1 NTN	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    2, 'precio_relativo' =>    140.00],
            ['codigo' =>    800046, 'nombre' => '	Rodamiento UCP205D1 NTN	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    2, 'precio_relativo' =>    155.00],
            ['codigo' =>    800034, 'nombre' => '	Rodamiento 608-2RSH SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    5, 'precio_relativo' =>    52.00],
            ['codigo' =>    800050, 'nombre' => '	Rodamiento 6001-2RSH/C3 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    5, 'precio_relativo' =>    70.00],
            ['codigo' =>    800018, 'nombre' => '	Rodamiento 6200-2RSH SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    10, 'precio_relativo' =>    56.00],
            ['codigo' =>    800062, 'nombre' => '	Rodamiento 6013-2RS1/C3 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    2, 'precio_relativo' =>    340.00],
            ['codigo' =>    800522, 'nombre' => '	Rodamiento 6020-2Z/C3 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    1, 'precio_relativo' =>    1444.04],
            ['codigo' =>    983913, 'nombre' => '	6-4722884401 Bearing NJ308ECP SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.00],
            ['codigo' =>    800349, 'nombre' => '	Rodamiento NUP-308-ECP SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    1, 'precio_relativo' =>    854.00],
            ['codigo' =>    800016, 'nombre' => '	Rodamiento 6307-2RS1 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    8, 'precio_relativo' =>    250.00],
            ['codigo' =>    800011, 'nombre' => '	Rodamiento 6306-2RS1 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    2, 'precio_relativo' =>    182.00],
            ['codigo' =>    800072, 'nombre' => '	CH-SNA Manguitos H-H 2309 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    1, 'precio_relativo' =>    390.00],
            ['codigo' =>    800051, 'nombre' => '	Rodamiento 6304-2RSH/C3 SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    2, 'precio_relativo' =>    60.00],
            ['codigo' =>    800009, 'nombre' => '	Rodamiento 6302-2RSH SKF	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    3, 'precio_relativo' =>    0.00],
            ['codigo' =>    800843, 'nombre' => '	Rodamiento 6303-2RSC3 CRAFT	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    10, 'precio_relativo' =>    30.00],
            ['codigo' =>    800071, 'nombre' => '	Rodamiento 6303-2RS ZKL	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A2)	', 'stock_minimo' =>    16, 'precio_relativo' =>    37.00],
            ['codigo' =>    800634, 'nombre' => '	Reten 15-25-7	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    10, 'precio_relativo' =>    25.00],
            ['codigo' =>    800602, 'nombre' => '	Reten AE3193F NOK	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    4, 'precio_relativo' =>    0.00],
            ['codigo' =>    800608, 'nombre' => '	Reten 30-47-7 SAV 7487	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    3, 'precio_relativo' =>    40.00],
            ['codigo' =>    800627, 'nombre' => '	Reten 30-40-7 BRUCE 551	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    4, 'precio_relativo' =>    30.00],
            ['codigo' =>    800614, 'nombre' => '	Reten 80-95-8 NAK	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.00],
            ['codigo' =>    983242, 'nombre' => '	Retentor Centrifugado Grande 7057	', 'descripcion' =>    NULL, 'observacion' => '	SOYA	pza (E-A4)	', 'stock_minimo' =>    10, 'precio_relativo' =>    924.04],
            ['codigo' =>    800600, 'nombre' => '	Reten 5718 ARCA	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    3, 'precio_relativo' =>    45.00],
            ['codigo' =>    800616, 'nombre' => '	Reten 80-95-10	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    0.00],
            ['codigo' =>    800601, 'nombre' => '	Reten 50-80-10 SAV 5200/24186	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    37.00],
            ['codigo' =>    800620, 'nombre' => '	Reten 25-40-7 TTO D014	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    3, 'precio_relativo' =>    25.00],
            ['codigo' =>    800615, 'nombre' => '	Reten 62-80-10 CRI	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.00],
            ['codigo' =>    800662, 'nombre' => '	Reten 38-56-8 Oil Seal	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    4, 'precio_relativo' =>    27.00],
            ['codigo' =>    800666, 'nombre' => '	Reten 38-52-7 ARCA 5009	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    4, 'precio_relativo' =>    21.00],
            ['codigo' =>    800612, 'nombre' => '	Reten 25-40-9 THO 	', 'descripcion' =>    '09283-25003/16634', 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    26.00],
            ['codigo' =>    800664, 'nombre' => '	Reten 50-68-9 02108	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    4, 'precio_relativo' =>    85.00],
            ['codigo' =>    800658, 'nombre' => '	Reten 50.8-69.88-9.52 SAV 5348	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    20.00],
            ['codigo' =>    800618, 'nombre' => '	Reten 60-80-8.5 ARCA 5990	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    1, 'precio_relativo' =>    38.00],
            ['codigo' =>    800644, 'nombre' => '	Reten 40-52-7 ARCA	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    1, 'precio_relativo' =>    26.00],
            ['codigo' =>    800633, 'nombre' => '	Reten 17-32-7 SAV	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.00],
            ['codigo' =>    800653, 'nombre' => '	Reten 30-47-7 ARCA 5069	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    1, 'precio_relativo' =>    37.00],
            ['codigo' =>    800646, 'nombre' => '	Reten 35-42-7 SAV 7210	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    4, 'precio_relativo' =>    14.00],
            ['codigo' =>    800621, 'nombre' => '	Reten 15-27-7 TO B714	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    3, 'precio_relativo' =>    0.00],
            ['codigo' =>    800609, 'nombre' => '	Reten 15-30-10 TTO C093	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    35.00],
            ['codigo' =>    800650, 'nombre' => '	Reten 17-32-7 ARCA 5374	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    3, 'precio_relativo' =>    20.00],
            ['codigo' =>    800647, 'nombre' => '	Reten 65-100-10 ARCA 5324/12405	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    47.00],
            ['codigo' =>    800643, 'nombre' => '	Reten 50-68-9 THO 50136 Metal	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    6, 'precio_relativo' =>    40.00],
            ['codigo' =>    983308, 'nombre' => '	Retentor 40-52-7	', 'descripcion' =>    NULL, 'observacion' => '	Eje Triturador SOYA	pza (E-A4)	', 'stock_minimo' =>    8, 'precio_relativo' =>    612.02],
            ['codigo' =>    800660, 'nombre' => '	Reten 28-40-8 D055-TTO/32162	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    1, 'precio_relativo' =>    22.00],
            ['codigo' =>    800636, 'nombre' => '	Reten 17-35-7 SAV 7141	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    20.00],
            ['codigo' =>    800629, 'nombre' => '	Reten 12-25-5 CRI	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    18, 'precio_relativo' =>    0.00],
            ['codigo' =>    800607, 'nombre' => '	Reten 30-40-8 SABO 00810	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    3, 'precio_relativo' =>    42.50],
            ['codigo' =>    800663, 'nombre' => '	Reten 25-35-8 SABO 02414/3368	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    5, 'precio_relativo' =>    52.28],
            ['codigo' =>    800628, 'nombre' => '	Reten 28-52.10-10 SABO 00503-BR	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    0.00],
            ['codigo' =>    800611, 'nombre' => '	Reten 20-32-7 SAV 15165/64010/19676	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    8, 'precio_relativo' =>    27.00],
            ['codigo' =>    802876, 'nombre' => '	Reten 50-68-9 MUSA T1341	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    16, 'precio_relativo' =>    93.00],
            ['codigo' =>    800604, 'nombre' => '	Reten 25-40-8 SAV 5053	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    3, 'precio_relativo' =>    21.00],
            ['codigo' =>    800648, 'nombre' => '	Reten 50-80-10	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    1, 'precio_relativo' =>    21.00],
            ['codigo' =>    802878, 'nombre' => '	Reten 20-32-7 ARCA 5614	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    6, 'precio_relativo' =>    40.00],
            ['codigo' =>    802915, 'nombre' => '	Reten 30.30-39.65-6.40 ARCA 5303	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    46.00],
            ['codigo' =>    800605, 'nombre' => '	Reten 20-32-8 SAV 5322	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    6, 'precio_relativo' =>    17.00],
            ['codigo' =>    800256, 'nombre' => '	Reten 40-56-7 SAV 6123	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    1, 'precio_relativo' =>    16.00],
            ['codigo' =>    800652, 'nombre' => '	Reten 17.5-28.5-7 SAV 5445	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    1, 'precio_relativo' =>    16.00],
            ['codigo' =>    800654, 'nombre' => '	Reten 30-47-10 SAV 5060	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    3, 'precio_relativo' =>    23.00],
            ['codigo' =>    800623, 'nombre' => '	Reten 17-28-7 MUSA F4226	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    58.00],
            ['codigo' =>    800717, 'nombre' => '	Reten 25-35-8 CRI 35812	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    44.00],
            ['codigo' =>    800645, 'nombre' => '	Reten 40-56-7 SUN 41670	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    2, 'precio_relativo' =>    34.00],
            ['codigo' =>    800619, 'nombre' => '	Reten 65-85-8 CRI 41578	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    1, 'precio_relativo' =>    32.00],
            ['codigo' =>    800635, 'nombre' => '	Reten 25-35-7 ARCA 5209	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (E-A4)	', 'stock_minimo' =>    4, 'precio_relativo' =>    20.00],
            ['codigo' =>    802722, 'nombre' => '	Tuerca Inox M12 Paso 1.75mm	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G19)	', 'stock_minimo' =>    1, 'precio_relativo' =>    3.14],
            ['codigo' =>    802654, 'nombre' => '	Tuerca Inox 3/4	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G19)	', 'stock_minimo' =>    5, 'precio_relativo' =>    15.03],
            ['codigo' =>    802489, 'nombre' => '	Aranddela M10 Dentada Din 6798 Cerrada 	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G20)	', 'stock_minimo' =>    2, 'precio_relativo' =>    2.81],
            ['codigo' =>    802490, 'nombre' => '	Arandela Dentada M12 Din 6798 Cerrada	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G20)	', 'stock_minimo' =>    1, 'precio_relativo' =>    3.30],
            ['codigo' =>    800781, 'nombre' => '	Tirafondo Hex 1/4x3/8	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G20)	', 'stock_minimo' =>    2, 'precio_relativo' =>    2.50],
            ['codigo' =>    802230, 'nombre' => '	Terminal TIPO Y 4x6mm SV5.5-6	', 'descripcion' =>    NULL, 'observacion' => '	Amarillo	pza (G23)	', 'stock_minimo' =>    21, 'precio_relativo' =>    0.49],
            ['codigo' =>    800768, 'nombre' => '	Terminal Ojal 1.5-2.5mm Diam 5.3mm	', 'descripcion' =>    NULL, 'observacion' => '	Azul	pza (G24)	', 'stock_minimo' =>    40, 'precio_relativo' =>    0.34],
            ['codigo' =>    801312, 'nombre' => '	Perno Inox Allen Cilindrico M6x60	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G27)	', 'stock_minimo' =>    4, 'precio_relativo' =>    2.83],
            ['codigo' =>    802648, 'nombre' => '	Prisionero Inox Allen M6x7mm	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G30)	', 'stock_minimo' =>    1, 'precio_relativo' =>    0.65],
            ['codigo' =>    800556, 'nombre' => '	Prisionero Inox Allen M8x16mm	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G31)	', 'stock_minimo' =>    1, 'precio_relativo' =>    2.50],
            ['codigo' =>    800539, 'nombre' => '	Tornillo Zincado 4.7x8mm	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G33)	', 'stock_minimo' =>    3, 'precio_relativo' =>    0.21],
            ['codigo' =>    801632, 'nombre' => '	Tuerca Inox M10 Paso 1.5mm	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G34)	', 'stock_minimo' =>    46, 'precio_relativo' =>    2.18],
            ['codigo' =>    801616, 'nombre' => '	Terminal Puenta Hueca 6mm	', 'descripcion' =>    NULL, 'observacion' => '	Rojo	pza (G35)	', 'stock_minimo' =>    96, 'precio_relativo' =>    0.36],
            ['codigo' =>    802794, 'nombre' => '	Conector DC	', 'descripcion' =>    NULL, 'observacion' => '	Macho y Hembra	pza (G36)	', 'stock_minimo' =>    1, 'precio_relativo' =>    5.00],
            ['codigo' =>    800347, 'nombre' => '	Arandela Plana de Acero 1 1/4	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G36)	', 'stock_minimo' =>    1, 'precio_relativo' =>    8.00],
            ['codigo' =>    802900, 'nombre' => '	Arandela Plana Inox 5/16	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G36)	', 'stock_minimo' =>    40, 'precio_relativo' =>    0.40],
            ['codigo' =>    802955, 'nombre' => '	Laina de Acero 0.25-17x25mm	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza (G36)	', 'stock_minimo' =>    14, 'precio_relativo' =>    2.25],
            ['codigo' =>    802979, 'nombre' => '	Spare X30 Printhead Assy ENM10069361	', 'descripcion' =>    NULL, 'observacion' => '	Control Experto	pza	', 'stock_minimo' =>    10, 'precio_relativo' =>    7126.00],
            ['codigo' =>    800434, 'nombre' => '	Tubo led T8 de 16w de 120cm	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	pza	', 'stock_minimo' =>    50, 'precio_relativo' =>    31.77],
            ['codigo' =>    800817, 'nombre' => '	Pintura Gris Anticorrosivo 	', 'descripcion' =>    NULL, 'observacion' => '	Ninguna	lts	', 'stock_minimo' =>    10, 'precio_relativo' =>    60.00],
        ],);
    }
}
